### ISSUE TITLE
[Bug] delete/update inner surround is broken

### ISSUE THREAD

**Issue by alex-popov-tech** [machakann/vim-sandwich#101]
Given:
```
console.log(ap|p, (app))
                         ^
```
When:
`sr([`
Then should be:
`console.log[ap|p, (app)]`
But actually was:
`console.log[app, [app))`
Delete works in the same fashion, like delete first two `(`

**Comment by machakann** [comment]
I could not reproduce the problem. Do you have any other settings?

![sandwich_issue101](https://user-images.githubusercontent.com/480049/90338840-6ae59a80-e027-11ea-90e1-ea54ef0b815b.gif)

**Comment by alex-popov-tech** [comment]
@machakann thanks for the answer!
here is plugin declaration
https://github.com/alex-popov-tech/.dotfiles/blob/master/nvim/plugins/core.vim#L35
and a single custom command
https://github.com/alex-popov-tech/.dotfiles/blob/master/nvim/plugins.vim
and thats pretty much all surround-like settings i have now...

Note: replace works in the same way as delete ( it replaces/deletes wrong pair )

**Comment by machakann** [comment]
OK, I've got. That's because of the setting written in #102 . The third line blows away all the default setting you copied. You need **+** in front of `=`.

```vim
let g:sandwich#recipes += [
  \   {
  \     'buns': ['(', ')'],
  \     'cursor': 'head',
  \     'command': ['startinsert'],
  \     'kind': ['add', 'replace'],
  \     'action': ['add'],
  \     'input': ['f']
  \   },
  \ ]
```

**Comment by alex-popov-tech** [comment]
oh, my bad, thank you!
