### ISSUE TITLE
[Bug] Undefined variable: g:sandwich#default_recipes

### ISSUE THREAD

**Issue by alex-popov-tech** [machakann/vim-sandwich#102]
Given:
```
Plug 'machakann/vim-sandwich'
let g:sandwich#recipes = deepcopy( g:sandwich#default_recipes )
let g:sandwich#recipes = [
  \   {
  \     'buns': ['(', ')'],
  \     'cursor': 'head',
  \     'command': ['startinsert'],
  \     'kind': ['add', 'replace'],
  \     'action': ['add'],
  \     'input': ['f']
  \   },
  \ ]

```
When: start vim
Then should be: no errors, `saiwfkek` should work as adding func call in insert mode with completion
But actually was error on startup:
```
Error detected while processing /Users/alexanderpopov/.config/nvim/plugins/core.vim:
line   36:
E121: Undefined variable: g:sandwich#default_recipes
E116: Invalid arguments for function deepcopy
E15: Invalid expression: deepcopy( g:sandwich#default_recipes )
```

**Comment by machakann** [comment]
This error simply tells that vim-sandwich is not in your `&runtimepath`. It seems you failed to install vim-sandwich, or I don't know much about vim-plug but you may need `call plug#end()` before `let g:sandwich#recipes = ~` since all plugins are not included in `&runtimepath` until the function called.

**Comment by alex-popov-tech** [comment]
after moving this snipped after plugin loading it worked...
but replacing does not work now, can you please show where cursor should be placed and whish keys should i use to replace `f` ?
like from `foo(kek)` to `bar(kek)`

**Comment by machakann** [comment]
If you want to replace `foo(kek)` to `bar(kek)`, you don't need any setting. So first remove the above recipe for `f` input and put the cursor anywhere on `foo(kek)` then type `srffbar<CR>`. You will see `bar(kek)` instead of `foo(kek)`. Tell me if you want something different.

**Comment by alex-popov-tech** [comment]
works nicely now, thanks!
