### ISSUE TITLE
[question] aliases for quoter and brackets?

### ISSUE THREAD

**Issue by alex-popov-tech** [machakann/vim-sandwich#103]
Hey, thanks for a great plugin!
Question - I could not figured out how to create aliases for different kind of pair characters, could you please help to build/add instruction to readme/add them by default?

Example:
- `q` for any kind of quotes (' " \`), so '"ke|k"' -> srq\` -> '\`ke|k\`'
- `b` for any kind of brackets ( [ ( { ), so ([ke|k]) -> srb{ -> ({ke|k})

**Comment by garymh** [comment]
Looking for this as well 😄

**Comment by singlexyz** [comment]
The sandwich has already implemented this function.
you only need to set the corresponding symbol in the buns with a regexp.

And this works for me.
```
let g:sandwich#recipes = deepcopy(g:sandwich#default_recipes)
let g:sandwich#recipes += [
      \   {
      \     'buns': ["[`'\"]\s*", "\s*[`'\"]"],
      \     'input'   : ['q'],
      \     'regex': 1,
      \   },
      \   {
      \     'buns': ["[\(\[\{]\s*", "\s*[\)\]\}]"],
      \     'input'   : ['b'],
      \     'regex': 1,
      \   },
      \ ]
```

**Comment by machakann** [comment]
See #145

**Comment by astier** [comment]
For people who use `target.vim` and want to use its builtin objects like `q` the following solution seems to work which was discussed in #92

```
let g:textobj_sandwich_no_default_key_mappings = 1
let g:sandwich_no_default_key_mappings = 1
nmap sa <plug>(operator-sandwich-add)
nmap sd <plug>(operator-sandwich-delete)A
nmap sr <plug>(operator-sandwich-replace)A
```

It has the additional benefit that for example `sr(` would search for the next match on line if the cursor is not within surrounding.
Not sure if this solution has any unwanted side-effects.

**Comment by astier** [comment]
Sadly it seems to break the magic character `f`. To make it work I had to add additionally:

```
nmap sdf <plug>(sandwich-delete)f
nmap srf <plug>(sandwich-replace)f
```
