### ISSUE TITLE
Changing/deleting a function should handle periods

### ISSUE THREAD

**Issue by xbe** [machakann/vim-sandwich#105]
I have:
```
foo.bar(car)
```

If I use "dsf" (with surround.vim bindings) around that element, I'd like to get:
```
car
```

Instead, I get:
```
foo.car
```

A similar problem happens when I try to change a function with "csf".

**Comment by machakann** [comment]
Hi. Depending on a language in one's mind, but probably you mean `foo` is a kind of instance (or might be a module), and `bar` is a method. Isn't it? I think there is a little room to discuss whether an instance should be regarded as a part of function (method?).

However, anyway, I can understand that could be useful in some cases. So if you want that kind of behavior, you can configure the vim-sandwich via `g:sandwich#magicchar#f#patterns` . It is a list of patterns telling "what is a function". If you want vim-sandwich to include something before a period as a part of function, you can add the lines in your vimrc:

```vim
	let g:sandwich#magicchar#f#patterns = [
	\   {
	\     'header' : '\<\%(\h\k*\.\)*\h\k*',
	\     'bra'    : '(',
	\     'ket'    : ')',
	\     'footer' : '',
	\   },
	\ ]
```

Probably you can find something in doc; [`:help sandwich-miscellaneous`](https://github.com/machakann/vim-sandwich/blob/f0bb324395bf6e00ec17fc7af60d2ccb8d494595/doc/sandwich.txt#L486)

**Comment by xbe** [comment]
Excellent, thank you!

>I think there is a little room to discuss whether an instance should be regarded as a part of function (method?).

Good point. I hadn't considered that.
