### ISSUE TITLE
Some recipe defaults in surround.vim are out of date

### ISSUE THREAD

**Issue by iFork** [machakann/vim-sandwich#106]
Some default recipes in `macros/sandwich/keymap/surround.vim ` seem to be out of date as compared with `autoload/sandwich.vim`.
Particularly recipes on double, single quotes and back-tick have `'match_syntax': 1` option which, as I understand, is problematic in some cases and is removed after #8, commit bb5a327, etc.
In my case issue was with double-quotes in markdown files.

**Comment by machakann** [comment]
Thanks, I updated. Please check the latest version.
