### ISSUE TITLE
sdf command can not delete complete function name

### ISSUE THREAD

**Issue by sillybun** [machakann/vim-sandwich#109]
For example:

```
self.__init__(a, b{cursor})
```
and press `sdf` will leave `self` out,

**Comment by machakann** [comment]
That's because `self` is neither a function nor a method. It's an instance. Anyway, you can change the behavior as you want. Use `g:sandwich#magicchar#f#patterns` or `b:sandwich_magicchar_f_patterns`. Check out `:help sandwich-miscellaneous` or #71, #105.

**Comment by sillybun** [comment]
Excellent, thank you!
