### ISSUE TITLE
g:sandwich#recipes undefined

### ISSUE THREAD

**Issue by swalladge** [machakann/vim-sandwich#11]
I have recently installed this and it worked wonderfully to begin with, until I wanted to add html tag surrounds to g:sandwich#recipes as per the readme.

```
E121: Undefined variable: g:sandwich#recipes
```

Ok, so I need to define it first in the vimrc, which works fine apart from the fact that vim-sandwich seems to ignore the default recipes when recipes is defined (so now `saiw(` turns `foo` into `(foo(` ).

The fix for me was to deepcopy g:sandwich#defaultrecipes to g:sandwich#recipes, then add more recipes to that (reference [inakacalm/.dotfiles](https://github.com/inakacalm/.dotfiles/blob/1ffc66a873eca67799858374b13f9f7fdb60efc3/.vimrc#L279) ).

Maybe this should be mentioned in the readme, or behaviour changed to keep the default recipes unless user specifically wants to override it.

**Comment by machakann** [comment]
Thank you for the suggestion. It looks the readme have not been so useful.

Now that I add some descriptions to keep default settings, as you did to copy g:sandwich#default_recipes to g:sandwich#recipes, because I want to leave a chance to make user-settings from scratch.

**Comment by swalladge** [comment]
Cool, that makes it nice and clear. :smiley:
