### ISSUE TITLE
Could you give a license this software?

### ISSUE THREAD

**Issue by yabuki** [machakann/vim-sandwich#110]
I heard vim-sandwich is great. I am checking this software. I am afraid that this software did not give any software license.

Author, Please consider give a license. if you mind, FLOSS license is good.

see also.

[Choose an open source license | Choose a License](https://choosealicense.com/)

**Comment by machakann** [comment]
https://github.com/machakann/vim-sandwich/blob/9e6340affe9f53c11a6975a5f50b9bf48adb692c/doc/sandwich.txt#L6

**Comment by yabuki** [comment]
Thank you!
