### ISSUE TITLE
Error when using f and t motions during sandwich add

### ISSUE THREAD

**Issue by ram02z** [machakann/vim-sandwich#111]
I have tried the motion using the surround binds and the normal binds. Once the error happens, the same motion can be completed without an error. I have been able to reproduce for the motions f, F, t and T. I have tested random characters using the motion and the error still occurs.

Using packer.nvim without any lazyloading on Neovim v0.5.0-dev.

See gif below for represenation.
The following keys were pressed(using the surround binds): `ysf'` (error shown) `ysf'{`
![sandwhich_motion](https://user-images.githubusercontent.com/59267627/120084855-8a881400-c0cb-11eb-9302-7f58a0fe050e.gif)

> Still image of the error

![image](https://user-images.githubusercontent.com/59267627/120084875-b73c2b80-c0cb-11eb-99ff-09fb117a4d66.png)

**Comment by ram02z** [comment]
I have not been able to reproduce the issue on a file with one line. I will continue to investigate and let you know.

**Comment by ram02z** [comment]
Turns out I was lazyloading the motions somewhere in my config. Sorry for the noise. 😅

**Comment by machakann** [comment]
Good to hear.
