### ISSUE TITLE
Deleting surrounding ~~ throws error

### ISSUE THREAD

**Issue by PROgram52bc** [machakann/vim-sandwich#113]
To reproduce the behavior:
1. open a new buffer with the following content
```
~~content~~
```
2. place the cursor anywhere inside the surrounding "~~"
3. in normal mode, type `dsi` (with the vim-surround mapping), and then `~~`, `~~`, for both prompts

The following error should occur:
```
textobj-sandwich:tail: ~~Error detected while processing function textobj#sandwich#select[12]..158[9]..159[5]..161[14]..176[1]..178:
line    1:
E33: No previous substitute regular expression
E33: No previous substitute regular expression
```

**Comment by machakann** [comment]
Fixed. Thanks!
