### ISSUE TITLE
How to convert th recipes part to lua format?

### ISSUE THREAD

**Issue by singlexyz** [machakann/vim-sandwich#115]
<img width="591" alt="图片" src="https://user-images.githubusercontent.com/4456413/131355615-17162985-51ad-40ea-b6bf-d86431eab24f.png">

**Comment by machakann** [comment]
You mean you want to define those recipes by lua interface in Neovim?

**Comment by singlexyz** [comment]
> You mean you want to define those recipes by lua interface in Neovim?

Yes, I think I should read the nvim-lua documentation.

**Comment by machakann** [comment]
Unfortunately, I'm not familiar with neither lua nor neovim, but it is just to set a global variable. There should be a way to do. Probably, `:help lua-vim-variables` might help.

**Comment by waikoo** [comment]
> If anyone comes across this, after lots of trial and error I have converted the [vim surround keybindings](https://github.com/machakann/vim-sandwich/wiki/Bracket-with-spaces) to Lua (I am using packer but this code can be used for other plugin managers too):
> 
> ```lua
>     use {
>       'machakann/vim-sandwich',
>       config = function()
>         -- Use vim surround-like keybindings
>         vim.cmd('runtime macros/sandwich/keymap/surround.vim')
>         -- '{' will insert space, '}' will not
>         vim.g['sandwich#recipes'] = vim.list_extend(vim.g['sandwich#recipes'], {
>           { buns = { '{ ', ' }' }, nesting = 1, match_syntax = 1, kind = { 'add', 'replace' }, action = { 'add' }, input = { '{' } },
>           { buns = { '[ ', ' ]' }, nesting = 1, match_syntax = 1, kind = { 'add', 'replace' }, action = { 'add' }, input = { '[' } },
>           { buns = { '( ', ' )' }, nesting = 1, match_syntax = 1, kind = { 'add', 'replace' }, action = { 'add' }, input = { '(' } },
>           { buns = { '{\\s*', '\\s*}' },     nesting = 1, regex = 1, match_syntax = 1, kind = { 'delete', 'replace', 'textobj' }, action = { 'delete' }, input = { '{' } },
>           { buns = { '\\[\\s*', '\\s*\\]' }, nesting = 1, regex = 1, match_syntax = 1, kind = { 'delete', 'replace', 'textobj' }, action = { 'delete' }, input = { '[' } },
>           { buns = { '(\\s*', '\\s*)' },     nesting = 1, regex = 1, match_syntax = 1, kind = { 'delete', 'replace', 'textobj' }, action = { 'delete' }, input = { '(' } }
>         })
>       end
>     }
> ```

Thanks for the plugin @machakann ! Thanks for the lua version @smjonas !
Could this be included [over here](https://github.com/machakann/vim-sandwich/wiki/Bracket-with-spaces) as well?

**Comment by machakann** [comment]
Yes, the Wiki page is not locked. Please feel free to edit.

**Comment by machakann** [comment]
Thanks!
