### ISSUE TITLE
Can't replace to tag properly

### ISSUE THREAD

**Issue by dantonyuk** [machakann/vim-sandwich#119]
When replacing some surroundings with a tag, it just puts the tag name without &lt; / &gt; symbols. E.g.

```
(asdf) --> pasdfp
```

when using `srbtp<CR>` or `sr(tp<CR>`. Am I doing anything wrong here?

**Comment by machakann** [comment]
Use `srbTp<CR>` or `sr(Tp<CR>` instead. The `t` only changes the name of tags, therefore it doesn't insert `<>`. `T` changes a whole tag body. Probably, `t` should check what is replaced to determine what to be inserted, I may improve for future.

**Comment by dantonyuk** [comment]
Got it, thank you! I went through the documentation and apparently was not able to find it, my bad.

Anyway, I keep this open for a while if you decide to change `srbt` behavior.

Thank you for the great plugin!
