### ISSUE TITLE
predot map no longer works

### ISSUE THREAD

**Issue by lervag** [machakann/vim-sandwich#12]
Hi. For some reason, the mapping

```vim
nmap . <plug>(operator-sandwich-predot)<plug>(RepeatDot)
```

no longer works. I use vim 7.4.1639 on Arch Linux, and the problem is reproduced with the following minimal vimrc file:

```vim
set nocompatible
let &rtp = '~/.vim/bundle/vim-repeat/,' . &rtp
let &rtp = '~/.vim/bundle/vim-sandwich/,' . &rtp
nmap . <plug>(operator-sandwich-predot)<plug>(RepeatDot)
```

See also #3 for reference.

**Comment by machakann** [comment]
Hi,
I realized that I have misunderstood about [vim-repeat](https://github.com/tpope/vim-repeat). The keymapping `<Plug>(RepeatDot)` is defined in a autoload script (`autoload/repeat.vim`), thus the keymapping does not exist until when other functions use `repeat#set()`.

I think public keymappings would be better to define in `plugin/repeat.vim`, but probably the author wanted to make it delayed loading as possible.

Anyway the following description may work, could you try?
```vim
nmap <expr> . hasmapto('<Plug>(RepeatDot)') ? '<Plug>(operator-sandwich-predot)<Plug>(RepeatDot)' : '<Plug>(operator-sandwich-dot)'
```

**Comment by machakann** [comment]
Now I am working on refactorings and bug fixes (including #7). So I will include revised documents together. Thanks!

**Comment by lervag** [comment]
Hmm, thanks. You answer seems good, but it did not explain why the mapping suddenly stopped working for me. So, I did a git bisect in my dotvim repo, and I noticed that things stopped working when I temporarily disabled a plugin. Your explanation is verified in that the plugin will call the `repeat#set()` function, and this happens before I define the mapping.

Thus, everything now works as expected when I have the plugin reenabled. Still, this has revealed an unexpected behaviour. I think your suggested solution is not quite what I want, since it will disable vim-repeat if it is not already activated. I think it will be better to first check if `<plug>(RepeatDot)` is defined, and if it is not, then we first source vim-repeat.

I think this should be mentioned in the docs, but I don't think you need to make any further updates.

**Comment by lervag** [comment]
Hmm. Perhaps even better: Define the mapping as suggested in the current version of the docs, but also add a `runtime autoload/repeat.vim` to ensure that vim-repeat is loaded. No need to check anything.

**Comment by machakann** [comment]
Excuse me, I tried and I found that, yes, what I suggested is not good aid for this problem...

Probably your solution would be better.
```vim
runtime autoload/repeat.vim		" Ensure that <Plug>(RepeatDot) is defined.
nmap . <Plug>(operator-sandwich-predot)<Plug>(RepeatDot)
```
Like this?

**Comment by lervag** [comment]
Yes, exactly!

Den fre. 25. mar. 2016, 14.15 skrev machakann <notifications@github.com>:

**Comment by machakann** [comment]
ok, I will close this issue when I update documents. Thank you!

**Comment by lervag** [comment]
Great! And thank you; I appreciate the effort and work you put into this plugin!

**Comment by Konfekt** [comment]
Had the same problem with repeat.vim at

https://github.com/tpope/vim-repeat/issues/40

and ended up having to add `runtime! autoload/repeat.vim` to `.vimrc`.

**Comment by machakann** [comment]
@Konfekt Thanks! I can agree with your opinion in the issue.

Anyway, now we can introduce the way to do with confident. That's good.

**Comment by machakann** [comment]
Thank you all!

**Comment by lervag** [comment]
Thanks yourself! :)
