### ISSUE TITLE
Is it possible to change the highlight color?

### ISSUE THREAD

**Issue by aamehedi** [machakann/vim-sandwich#121]
## Is it possible to change the highlight color for this plugin.
I really love the highlight feature as it gives me a feedback before actually executing. But the only problem I am facing that the highlight color is too dark for my colorscheme. I am using Tokyonight.
Thanks for making this plugin.

**Comment by machakann** [comment]
Yes, as @bew says, please use `OperatorSandwichAdd` and `OperatorSandwichDelete` groups. One way is to link to another group other than `DiffAdd`:
```vim
highlight link OperatorSandwichAdd Visual
```

Or, specify the colors explicitly:
```vim
highlight OperatorSandwichAdd ctermfg=White ctermbg=Red guifg=White   guibg=Red
```

**Comment by aamehedi** [comment]
hi, sorry for my late reply.
It all worked out. Thanks a lot. In addition to the highlight groups `OperatorSandwichAdd` and `OperatorSandwichDelete`, I also used `OperatorSandwichChange` to make it look cool :)
