### ISSUE TITLE
[Feature Request] User defined `timeout` and `timeoutlen` for mappings 

### ISSUE THREAD

**Issue by luiz00martins** [machakann/vim-sandwich#123]
In my setup, I disable `timeout` and `ttimeout`, so if I stop in the middle of a mapping, vim will just wait for the next press, instead of eating what's there. I noticed that sandwich does not adjust to those options, and I couldn't find a way to change that in the docs.

For example, I have the mappings `sbf`, `sbi`, and `sbe` for wrapping lines around `for { ... }`, `if { ... }`, and `else { ... }` blocks. Hovewer, if I press `sb`, and take too long for my next press, sandwich will eagerly wrap the lines with `b ... b`.

I'd be nice if sandwich adjusted to the timeout options (i.e. `timeout`, `ttimeout`, `timeoutlen`, and `ttimeoutlen`), or if they were manually configurable.

**Comment by machakann** [comment]
Thanks, indeed sandwich.vim should see the `'timeout'` option. I will fix it.

**Comment by machakann** [comment]
Now, sandwich.vim refers `'timeout'` option. If `:set notimeout`, operators will wait for the next key sequence until a recipe is specified. Also, I add `g:sandwich#timeout` option for plugin-private config. It can be used instead of the `'timeout'` option.

```vim
let g:sandwich#timeout = 0
```

**Comment by luiz00martins** [comment]
Hi! Sorry for leaving you waiting.

Just updated, and have confirmed that sandwich.vim now respects the `timeout` option.

Thanks a lot for the update!!
