### ISSUE TITLE
linewise always include whole line.

### ISSUE THREAD

**Issue by singlexyz** [machakann/vim-sandwich#128]
For example, I have this text below:
```jsx
{
  showHeader && <Suspense fallback={null}>
    <Header />
  </Suspense>
}
```
and I want to change to this:
```jsx
{
  showHeader && (
    <Suspense fallback={null}>
      <Header />
    </Suspense>
  )
}
```

Then I press `saat)` on `<Suspense...`
![ezgif-6-123](https://user-images.githubusercontent.com/4456413/145029332-ad8b5cf0-d66e-4783-be7b-6478ff841d4b.gif)

Sandwich will put `(` in front of the entire line, instead of inserting in front of the selected textobj.

Config:
```vim
\   {
\     'buns': ['(', ')'],
\     'input'   : [')'],
\     'linewise'    : 1,
\   },
```

**Comment by machakann** [comment]
The option always works line-wise. Thus, never insert a parenthesis in the middle of a line. Probably, what you want is:
```
\   {
\     'buns': ["(\n", "\n)"],
\     'input' : [')'],
\     'command': ["'[+1,']-1normal! >>"]
\   },
```
Note that `command` option may cause wrong highlight.

**Comment by singlexyz** [comment]
> 



> 



> The option always works line-wise. Thus, never insert a parenthesis in the middle of a line. Probably, what you want is:
> 
> ```
> \   {
> \     'buns': ["(\n", "\n)"],
> \     'input' : [')'],
> \     'command': ["'[+1,']-1normal! >>"]
> \   },
> ```
> 
> Note that `command` option may cause wrong highlight.

Thanks, it works.
I also replaced the line with `\n` generation before, but it directly output `(\n`.
```vim
'buns': ['(\n', '\n)'],
```
Then I found out that you used double quotes. After I changed it, it was escaped.
