### ISSUE TITLE
suggest vim-surround mappings for newcomers

### ISSUE THREAD

**Issue by Konfekt** [machakann/vim-sandwich#13]
Your plugin is great as
- `<Plug>(textobj-sandwich-literal-query-i)` and `<Plug>(textobj-sandwich-literal-query-a)` replace https://github.com/thinca/vim-textobj-between
- `<Plug>(textobj-sandwich-auto-i)` and `<Plug>(textobj-sandwich-auto-a)` replace https://github.com/rhysd/vim-textobj-anyblock, and finally
- of course https://github.com/tpope/vim-surround can be replaced, but the mappings are a bit difficult to setup. Perhaps the following setup could be proposed in the README or doc for everyone willing to convert from vim-surround to vim-sandwich:

```vim
let g:sandwich_no_default_key_mappings = 1
let g:operator_sandwich_no_default_key_mappings = 1
let g:textobj_sandwich_no_default_key_mappings = 1

nmap ys <Plug>(operator-sandwich-add)
onoremap <SID>line :normal! ^vg_<CR>
nmap yss <Plug>(operator-sandwich-add)<SID>line
onoremap <SID>gul g_
nmap yS  ys<SID>gul

nmap ds <Plug>(operator-sandwich-delete)<Plug>(textobj-sandwich-query-a)
nmap dss <Plug>(operator-sandwich-delete)<Plug>(textobj-sandwich-auto-a)
nmap cs <Plug>(operator-sandwich-replace)<Plug>(textobj-sandwich-query-a)
nmap css <Plug>(operator-sandwich-replace)<Plug>(textobj-sandwich-auto-a)

xmap S <Plug>(operator-sandwich-add)

xmap is <Plug>(textobj-sandwich-auto-i)
xmap as <Plug>(textobj-sandwich-auto-a)
omap is <Plug>(textobj-sandwich-auto-i)
omap as <Plug>(textobj-sandwich-auto-a)

xmap im <Plug>(textobj-sandwich-literal-query-i)
xmap am <Plug>(textobj-sandwich-literal-query-a)
omap im <Plug>(textobj-sandwich-literal-query-i)
omap am <Plug>(textobj-sandwich-literal-query-a)

nmap . <Plug>(operator-sandwich-predot)<Plug>(RepeatDot)
" runtime! autoload/repeat.vim

" Default recipes
let g:sandwich#recipes = [
                  \   {
                  \     'buns':         ['<', '>'],
                  \     'expand_range': 0,
                  \     'match_syntax': 1,
                  \     'input':        ['a'],
                  \   },
                  \
                  \   {
                  \     'buns':         ['"', '"'],
                  \     'quoteescape':  1,
                  \     'expand_range': 0,
                  \     'nesting':      0,
                  \     'linewise':     0,
                  \     'match_syntax': 1,
                  \   },
                  \
                  \   {
                  \     'buns':         ["'", "'"],
                  \     'quoteescape':  1,
                  \     'expand_range': 0,
                  \     'nesting':      0,
                  \     'linewise':     0,
                  \     'match_syntax': 1,
                  \   },
                  \
                  \   {
                  \     'buns':         ['{', '}'],
                  \     'nesting':      1,
                  \     'match_syntax': 1,
                  \     'skip_break':   1,
                  \     'input':        ['B'],
                  \   },
                  \
                  \   {
                  \     'buns':         ['[', ']'],
                  \     'nesting':      1,
                  \     'match_syntax': 1,
                  \     'input':        ['r'],
                  \   },
                  \
                  \   {
                  \     'buns':         ['(', ')'],
                  \     'nesting':      1,
                  \     'match_syntax': 1,
                  \     'input':        ['b'],
                  \   },
                  \ ]
```

**Comment by machakann** [comment]
Yes, these days I realized the problem. I'd like to put degrees of freedom as possible, but it is not so kind for newcomers currently. Also I can understand the need for the mappings same with [vim-surround](https://github.com/tpope/vim-surround).

I plan to put the descriptions for newcomer in documents. I will also write similar one to README.md or open [wiki](https://github.com/machakann/vim-sandwich/wiki) and introduce it in README.md with a link. Let me think. Of course, any ideas will be welcome!

**Comment by lervag** [comment]
I'm also considering (and currently testing) to go back to the surround.vim default keys. I think I might find them preferable. The only problem is I don't like the `ys`, beause it is "hard" to type.

Anyway, I want to suggest the following mappings as an alternative to the corresponding suggestion from @Konfekt:

```vim
xmap is  <plug>(textobj-sandwich-query-i)
xmap as  <plug>(textobj-sandwich-query-a)
omap is  <plug>(textobj-sandwich-query-i)
omap as  <plug>(textobj-sandwich-query-a)
xmap iss <plug>(textobj-sandwich-auto-i)
xmap ass <plug>(textobj-sandwich-auto-a)
omap iss <plug>(textobj-sandwich-auto-i)
omap ass <plug>(textobj-sandwich-auto-a)
```

The point is to allow e.g. `dis]`, which can often be very convenient!

**Comment by Konfekt** [comment]
Regarding the inconvenient mapping ys, how about instead using gs whose default functionality is disposable.

**Comment by Konfekt** [comment]
Instead if You surround, the mnemonic becomes Get surrounded.

**Comment by lervag** [comment]
Hmm, that's a good idea. Thanks!

**Comment by machakann** [comment]
Hi.

To avoid confusion, I will introduce each kind of textobjects supplementary. Because vim-surround it self do not have independent textobjects. (Though I also think these are very convenient!) It will be put somewhere easily to be seen, probably just after the introduction of vim-surround style mappings.

By the way, I remember that vim-surround adds braket with inner spaces by `(`, and adds braket without space by `)`. I am wondering that it might be natural for them to reproduce the behavior. Isn't it?

**Comment by lervag** [comment]
Personally I never want to include the inner spaces, but it doesn't hurt to allow that and show how to get similar functionality to vim-surround.

**Comment by Konfekt** [comment]
As an aside, I am grateful that Sandwich does not insist on hitting space twice to surround by spaces.

**Comment by machakann** [comment]
ok, now it's clear.

**Comment by machakann** [comment]
I add a file as preset in `macros` folder. Probably it is easier to use for newcomers and never disturb others. Use this as following.
```vim
runtime macros/sandwich/keymap/surround.vim
```

Also I add link in README.md to the [wiki page](https://github.com/machakann/vim-sandwich/wiki/Introduce-vim-surround-keymappings) which introduce the way to use the preset.

**Comment by Konfekt** [comment]
Awesome. You should announce it on reddit. This plug-in deserves some publicity.

**Comment by machakann** [comment]
Thanks, after fixing several minor bugs, I will think of it.
