### ISSUE TITLE
How to disable in Telescope prompt?

### ISSUE THREAD

**Issue by demon386** [machakann/vim-sandwich#131]
It would like to disable the plugin to avoid pairing `'` in the filemode TelescopePrompt.

**Comment by machakann** [comment]
Excuse me, I'm not sure what kind of function you meant. Is it a function like auto-closing `''` pairs?

**Comment by demon386** [comment]
> Excuse me, I'm not sure what kind of function you meant. Is it a function like auto-closing `''` pairs?

Yes. I want to disable auto-closing '' pairs when launch a prompt window in Telescope.

**Comment by machakann** [comment]
OK, I guess it's not sandwich's functionality. Sandwich.vim does not provide auto-closing feature.

**Comment by demon386** [comment]
My bad. It has nothing to do with vim-sandwich. Sorry for the noise.
