### ISSUE TITLE
[Sugesstion] Disable `sandwich-add` in Select mode

### ISSUE THREAD

**Issue by chiendo97** [machakann/vim-sandwich#132]
With the default key mapping, it will enable `sandwich-add` mapping in Select mode. 

It's a bit annoying when I use the snippets feature, I will be in Select-mode then I press `s`, it will add a timeout to replace the currently selected words to `s` character. 

My segesstion is insead of mapping 
````
silent! map <unique> sa <Plug>(sandwich-add)`
```
we should use 
```
  silent! nmap <unique> sa <Plug>(sandwich-add)
  silent! xmap <unique> sa <Plug>(sandwich-add)
``` by default. 

Thank you.

**Comment by machakann** [comment]
Thank you for your report!

You are right. This is not intended. Please try the latest version.

**Comment by chiendo97** [comment]
Thank you so much for your updates. 
I will update my plugin now.
