### ISSUE TITLE
<Plug>(textobj-sandwich-literal-query-i/a)

### ISSUE THREAD

**Issue by Konfekt** [machakann/vim-sandwich#14]
To replace https://github.com/thinca/vim-textobj-between, there could be maps  `<Plug>(textobj-sandwich-literal-query-i)` and `<Plug>(textobj-sandwich-literal-query-a)` that ignore `g:sandwich#recipes`. Otherwise the `input` option interferes, for example `input: ['b']` for the `(,)` bun.

**Comment by machakann** [comment]
Hmm... I thought that it was possible, but actually it is not...

**Comment by machakann** [comment]
The problem is the fourth argument of the function `textobj#sandwich#query()`.

If user gives a list to the fourth argument to make a keymapping, it uses the list instead of `g:sandwich#recipes`. However if the list is empty, the keymapping yet uses `g:sandwich#recipes`. It is not a reasonable behavior, an empty list should be also effective. That is, the suggested keymapping should be realized by:
```vim
onoremap <silent><expr> <Plug>(textobj-sandwich-literal-query-i) textobj#sandwich#query('o', 'i', {}, [])
xnoremap <silent><expr> <Plug>(textobj-sandwich-literal-query-i) textobj#sandwich#query('x', 'i', {}, [])
onoremap <silent><expr> <Plug>(textobj-sandwich-literal-query-a) textobj#sandwich#query('o', 'a', {}, [])
xnoremap <silent><expr> <Plug>(textobj-sandwich-literal-query-a) textobj#sandwich#query('x', 'a', {}, [])
```
I will review my code for that.

**Comment by Konfekt** [comment]
Ok, for the moment
```vim
onoremap <silent><expr> <Plug>(textobj-sandwich-literal-query-i) textobj#sandwich#query('o', 'i', {}, g:sandwich#default_recipes)
xnoremap <silent><expr> <Plug>(textobj-sandwich-literal-query-i) textobj#sandwich#query('x', 'i', {}, g:sandwich#default_recipes)
onoremap <silent><expr> <Plug>(textobj-sandwich-literal-query-a) textobj#sandwich#query('o', 'a', {}, g:sandwich#default_recipes)
xnoremap <silent><expr> <Plug>(textobj-sandwich-literal-query-a) textobj#sandwich#query('x', 'a', {}, g:sandwich#default_recipes)
```
works perfectly fine. Perhaps add these by default?!

**Comment by machakann** [comment]
Wait a moment, probably these mappings have been still affected by `g:sandwich#recipes`.

**Comment by machakann** [comment]
OK, it is fixed, and it sounds convenient so I added the keymappings. Use like this:
```vim
omap if <Plug>(textobj-sandwich-literal-query-i)
xmap if <Plug>(textobj-sandwich-literal-query-i)
omap af <Plug>(textobj-sandwich-literal-query-a)
xmap af <Plug>(textobj-sandwich-literal-query-a)
```
Substitute `if` and `af` as you like.

**Comment by Konfekt** [comment]
Ok. True. Usually 'im' = inner method and NOT 'if' = inner function.
