### ISSUE TITLE
How to omit last parameter?

### ISSUE THREAD

**Issue by singlexyz** [machakann/vim-sandwich#146]
Normally, to use the add function, I would use `saiw'` to add single quotes to the current word.

But if I want to simply use `'iw` to implement, I can omit some keys.

That is, I mapped `'` to `<Plug>(sandwich-add)`, But I still have to press `'iw'`.

```vim
nmap ' <Plug>(sandwich-add)
```

In other words, I want to change the order of the key press, enter the surrounding first, then enter the textobj.

**Comment by machakann** [comment]
Probably, you can use `<Plug>(operator-sandwich-add-query1st)` instead of `<Plug>(sandwich-add)`? I personally use the mappings below.

```vim
nmap s' <Plug>(operator-sandwich-add-query1st)'
xmap s' <Plug>(operator-sandwich-add)'
```

**Comment by singlexyz** [comment]
> Probably, you can use `<Plug>(operator-sandwich-add-query1st)` instead of `<Plug>(sandwich-add)`? I personally use the mappings below.
> 
> ```viml
> nmap s' <Plug>(operator-sandwich-add-query1st)'
> xmap s' <Plug>(operator-sandwich-add)'
> ```

Yeah, that's it. This saves a lot of keys.
```
nnoremap ' <Plug>(operator-sandwich-add-query1st)'
nnoremap ` <Plug>(operator-sandwich-add-query1st)`
nnoremap " <Plug>(operator-sandwich-add-query1st)"
nnoremap ( <Plug>(operator-sandwich-add-query1st)(
nnoremap [ <Plug>(operator-sandwich-add-query1st)[
nnoremap { <Plug>(operator-sandwich-add-query1st){
```
