### ISSUE TITLE
`v:errmsg` is set when `visualrepeat` is not installed

### ISSUE THREAD

**Issue by smjonas** [machakann/vim-sandwich#147]
Hey, I just noticed this issue while working on a plugin that can preview commands such as `:norm`. This is probably a Neovim-only issue but I thought I'd report it anyway.

## Reproduction steps
**Neovim 0.8 nightly version is required for this.**

1. Make sure the following Lua code gets run (e.g. put it at the top of `init.lua`) - I did not change any vim-sandwich defaults. This simply runs the command `: norm saw]` inside the preview callback function of a user command.
 
```lua
local on_execute_command = function(_)
  print("Error encountered inside preview function: " .. vim.v.errmsg)
end

vim.api.nvim_create_user_command("TestCmd", on_execute_command, {
  preview = function(_, _, _)
    vim.v.errmsg = ""
    vim.cmd("norm saw]")
    return 2
  end,
})
```
3. Run `:TestCmd`.

### Actual behavior
The following error is printed which was caused inside of the preview callback (that is what `vim.v.errmsg` is for): 
`Error encountered inside preview function:E117: Unknown function: visualrepeat#set`.

### Expected behavior
No errors should occur inside the preview function. 

### Additional context
The preview is shown correctly, the only problem I have is that `vim.v.errmsg` is set. No error is set when [inkarkat/vim-visualrepeat](https://github.com/inkarkat/vim-visualrepeat) is installed.

**Comment by machakann** [comment]
Thanks. Currently, it is not easy for me to reproduce the problem since I have no neovim environment. However, it sounds strange to get the error, because the `visualrepeat#set` is called with `:silent!`. Mmm...

Maybe, visualrepeat should be enabled only when user explicitly declare the use of the plugin. I will update hopefully in a few days.

**Comment by machakann** [comment]
The problem is probably solved. Please feel free to reopen if you found any problems again.

**Comment by smjonas** [comment]
Thank you very much for fixing it so quickly, there's no error anymore!
