### ISSUE TITLE
Replace command not working with HTML tag on multiple lines

### ISSUE THREAD

**Issue by kenta-ja8** [machakann/vim-sandwich#149]
First of all, thanks for the great plugin.

The replace command does not work as expected.
For example, I replace `button` to `span`.

Code:
```
<button :class="{
  class-a: true,
  class-b: true,
">
  PUSH
</button>
```
Type: `srttspan`

Expected:
```
<span :class="{
  class-a: true,
  class-b: true,
">
  PUSH
</span>

```

Actual:
```
<<span> :class="{
   class-a: true,
   class-b: true,
 }">
   PUSH
 </</span>>

```

I tested the old commit and got the following results.

- 7bdd7fc not work
- f3f7542 work as expected

### Environment
- vim-sandwich 59f95e6
- NVIM v0.7.0

**Comment by machakann** [comment]
Thanks, this is a bug. I have reverted the commit.
