### ISSUE TITLE
`dsf` in vim-surround keybindings not implemented

### ISSUE THREAD

**Issue by YuruiHong** [machakann/vim-sandwich#168]
It is nice to see that vim-surround keybindings are supported. However, while addition of functions via `ysiwf` is available, `dsf` or `dsF` are not. The original keybindings do include `sdf` and `sdF`, so I wonder if it is possible to have them implemented for the vim-surround one.

**Comment by Konfekt** [comment]
Are `sdf` and `sdF` any different from vim-surround's `dsf` and `sdF` ? When these keybindings were listed, its author might simply not have been aware of them

**Comment by Konfekt** [comment]
It started of [here](https://github.com/machakann/vim-sandwich/issues/13) but since them the mappings were refined many times

**Comment by YuruiHong** [comment]
It seems there's no bug at all. I just found that I didn't remove my `tpope/vim-surround`, which was actually providing vim-surround keybindings without `dsf` and blocking `vim-sandwich`. My fault.🤣
