### ISSUE TITLE
Announce: release of "Magic characters"

### ISSUE THREAD

**Issue by machakann** [machakann/vim-sandwich#18]
Hi, I'm happy to introduce new members of default recipes. Those are, probably, somehow versatile or widely used, thus I think it is worth adding to default recipes.

- Function-surroundings
- Instant-surroundings
- HTML style tags

If you are interested, please check wiki [here](https://github.com/machakann/vim-sandwich/wiki/Magic-characters)!

Those new features might not have been matured yet, so I will keep on making it better. If you have any ideas, feel free to tell me here or another issue. Thanks!

**Comment by lervag** [comment]
Very nice! This will be very useful!

I notice that after e.g. `saiwf...`, the cursor disappears. I could try to explain in more detail how to reproduce (e.g. with minimal example) if you can't reproduce this.

**Comment by machakann** [comment]
I'm glad to hear that.

Let me ask about the problem, is the cursor disappears permanently or temporary?

**Comment by lervag** [comment]
Temporary, until any motion or action.

Den lør. 13. aug. 2016, 12.47 skrev machakann <notifications@github.com>:

**Comment by machakann** [comment]
I couldn't have reproduced, mmm... I slightly revised doubtful points, could you test the latest version?

**Comment by lervag** [comment]
The following minimal vimrc file suffices for me to reproduce:

```vim
set nocompatible
let &rtp = '~/.vim/bundle/vim-sandwich,' . &rtp
set guicursor+=a:blinkon0
```

As you can see, this affects the gui version. I now do: `gvim -u minivimrc`, then I write "test", then do `saiwffunc<cr>`. The result is that the cursor is no longer displayed. The cursor is displayed again as soon as I do anything.

**Comment by lervag** [comment]
Oh, and by the way, the latest version still does not work.

**Comment by machakann** [comment]
Thanks! Maybe I've got the problem. Please check the latest one.

**Comment by lervag** [comment]
Yes, works now. Thanks!
