### ISSUE TITLE
Add support for visualrepeat (script_id=3848)

### ISSUE THREAD

**Issue by kiryph** [machakann/vim-sandwich#19]
I really appreciate the support for dot repeat. Have you ever considered to support visualrepeat by Ingo Karkat (http://www.vim.org/scripts/script.php?script_id=3848)?

```
==============================================================================
INTEGRATION					    *visualrepeat-integration*

This plugin is meant to be used together with repeat.vim.

This plugin has helper functions that plugins with cross-repeat functionality
can use in their normal mode repeat mappings of repeated visual mode mappings.
With this, you save work and allow for a consistent user experience.
Define your normal mode repeat mapping like this: >
    nnoremap <silent> <Plug>(MyPluginVisual)
    \ :<C-u>execute 'normal!' visualrepeat#reapply#VisualMode(0)<Bar>
    \call MyPlugin#Operator('visual', "\<lt>Plug>(MyPluginVisual)")<CR>
If your plugin uses a passed [count] (i.e. the count is not only used to
determine the text area the mapping is applied to), you need to define a
mapping: >
    vnoremap <silent> <expr> <SID>(ReapplyRepeatCount) visualrepeat#reapply#RepeatCount()
and apply the function followed by the mapping like this: >
    nnoremap <silent> <script> <Plug>(MyPluginVisual)
    \ :<C-u>execute 'normal!' visualrepeat#reapply#VisualMode(1)<CR>
    \<SID>(ReapplyRepeatCount)
    \:<C-u>call MyPlugin#Operator('visual', v:count, "\<lt>Plug>(MyPluginVisual)")<CR>
If you want to support running without visualrepeat.vim, too, provide a
wrapper that defaults to |1v|: >
    function! s:VisualMode()
	let l:keys = "1v\<Esc>"
	silent! let l:keys = visualrepeat#reapply#VisualMode(0)
	return l:keys
    endfunction
    nnoremap <silent> <Plug>(MyPluginVisual)
    \ :<C-u>execute 'normal!' <SID>VisualMode()<Bar>
    \call MyPlugin#Operator('visual', "\<lt>Plug>(MyPluginVisual)")<CR>
```

**Comment by machakann** [comment]
Thanks! I haven't found that plugin. Actually I still don't know what it does, probably I will check whether I can support it later. I would be busy for a few days, sorry!

**Comment by kiryph** [comment]
Hey, don't worry. If you like it and you can add support for it in the long run, I am more than happy.
I have created also an issue https://github.com/tpope/vim-surround/issues/121 for vim-surround by tpope in Feb 2014. Tpope never responded to this. Looking at his current public github activity it is not very likely that things change.

Anyhow, I'd like to add a usage example when surrounding different objects with tags:

```
(0)This text is a copy from an arbitrary source. Some html markup is missing such as (1)italic
and bold face.(3) (2)A whole sentence in italic. Bold words!(4)
```

I use surround style mappings to add missing markup which gives me following editing key sequence:

1. `/italic<cr>` (0)->(1)
2. `ysiwtem` (surround `italic` with `<em></em>`)
3. `)` (1)->(2)
4. `vis.` (This does not work yet. This would require visualrepeat.)
5. `b` (2)->(3)
6. `vbbStstrong` (surround `bold face` with `<strong></strong>`)
7. `$` (3)->(4)
8. `vis.` (This does not work yet. This would require visualrepeat.)

Right now, I use following two plugins which have already support for visualrepeat:

- `ReplaceWithRegister` by IngoKarkat
- `easy-align` by Junegunn

Example for `ReplaceWithRegister`:

```
yank mountain and replace at several places: forest, beach, lonely island
```
following editing sequence
```
1. /mountain
2. yiw
3. /forest
4. griw
5. W
6. .
7. Wvee
8. .
```
gives
```
yank mountain and replace at several places: mountain, mountain, mountain
```

**Comment by machakann** [comment]
Very clear and it looks useful. OK, I need some time but we will get luck probably.

**Comment by machakann** [comment]
I just finished to implement visualrepeat.vim support. I'm not really sure it works or not, could you test it?

If you find something strange behavior, please let me know anytime.

**Comment by kiryph** [comment]
I have repeated my example given above with the html tags. And YES IT WORKS. That's great. Thank you very much.

When I encounter anything strange, I will let you know. In the meantime happy coding.
