### ISSUE TITLE
Unexpected <Enter> treatment

### ISSUE THREAD

**Issue by sudo-nice** [machakann/vim-sandwich#20]
Hello, thank you for a great plugin! I'd like to use it to surround a line with
empty lines, but something unexpected happens. Steps to reproduce:
Have a file with three lines:
```
first
second
third
```

Stay on the second line and press `VS<Enter>` (I have surround macro
enabled: `runtime macros/sandwich/keymap/surround.vim`)

Expected result:
```
first
<empty>
second
<empty>
third
```

Actual result:
```
first
<empty>
<empty>
<empty>
<empty>
second
third
```

I'm on neovim 0.15, but not sure if it matters.

**Comment by machakann** [comment]
Thank you, I reproduced it. It is a bug actually, I will handle this.

**Comment by machakann** [comment]
OK, the bug has been fixed, but to be exact the expected result is:
```
first
<empty>
<empty>
second
<empty>
<empty>
third
```
Because, in linewise-visual mode, add string linewise, in other words "add new line and more put what you input, a linebreak here". However, actually, the exact action is not so convenient. So I will make it better later.

**Comment by sudo-nice** [comment]
Oh, I see, thank you.

**Comment by machakann** [comment]
OK, it should work as you expected. It looks helpful also for me. Please test that **VS\<Enter\>** works correctly  after updating sandwich.vim. Also you can do **ds\<Enter\>** to delete nearest empty lines.

I added the new default recipes, just for your info.
```vim
let g:sandwich#default_recipes += [
      \   {'buns': ['', ''], 'action': ['add'], 'motionwise': ['line'], 'linewise': 1, 'input': ["\<CR>"]},
      \   {'buns': ['^$', '^$'], 'regex': 1, 'linewise': 1, 'input': ["\<CR>"]},
    ]
```

**Comment by sudo-nice** [comment]
It works perfect here, thank you!

**Comment by machakann** [comment]
Welcome!
