### ISSUE TITLE
sr" and sd" are not working anymore

### ISSUE THREAD

**Issue by KabbAmine** [machakann/vim-sandwich#25]
I cannot said from which commit it started, but `sr"` and `sd"` are not working anymore, but using `srb`/`sdb` works.

- Vim `8.0.22`
- My vim-sandwich config:
```vim
" >>> (( vim-sandwich )) {{{1
call operator#sandwich#set('all', 'all', 'cursor', 'keep')
call operator#sandwich#set('all', 'all', 'hi_duration', 50)
vmap v ab
" Allow using . with the keep cursor option enabled
nmap . <Plug>(operator-sandwich-dot)
hi link OperatorSandwichStuff StatusLine
```

Note that the same issue occurs with a minimal vimrc.

**Comment by sudo-nice** [comment]
I've made some investigation and believe the bug is introduced with 1fa1910

**Comment by KabbAmine** [comment]
Yes, rolling back to ee19eec1b384615d09605d91eaf319b1d114d5ec makes it work normally.

**Comment by machakann** [comment]
Thanks! It seems because of an old bug unrealized ever, it emerges after 1fa19101f8e7388879ec2437bb18b2141c8a4862. Probably it has fixed now.

**Comment by KabbAmine** [comment]
6ea5089 fixed it, thanks.
