### ISSUE TITLE
Replacing surroundings with a tag (feature request).

### ISSUE THREAD

**Issue by sudo-nice** [machakann/vim-sandwich#26]
Given an example line with the cursor somewhere inside it: `[foo bar]`
Try to replace the brackets with the <baz> tag `sr ] t baz <cr>` (spaces are for convenience)
But instead of `<baz>foo baz</baz>` you get `bazfoo barbaz`

Maybe you would like to implement such an option.

**Comment by machakann** [comment]
If you want to replace into whole tags, you can use **T** input instead of **t** : `sr ] T baz <cr>`.

**Comment by sudo-nice** [comment]
Oh, I've overlooked that... Thank you!
