### ISSUE TITLE
Removed multiline tag leaved trailing angle bracket.

### ISSUE THREAD

**Issue by sudo-nice** [machakann/vim-sandwich#27]
Testing of this awesome plugin is in progress, so I brought you another question. Here is the example with the cursor inside the word `foo`:
```
<?xml version="1.0" encoding="UTF-8"?>
<section>
  <cite>
    <p>foo</p>
    <p>bar</p>
  </cite>
</section>
```
Now, if we press `2sdt` or `2sdT`, we get this:
```
<?xml version="1.0" encoding="UTF-8"?>
<section>
  >
    <p>foo</p>
    <p>bar</p>
  
</section>
```
I'm confused with that `>`. Am I missing something?

**Comment by machakann** [comment]
Thank you for your report, it looks a bug. The last `>` should removed.

Do you think it is useful to remove the empty lines?

**Comment by machakann** [comment]
* Do not remove ( `-` represents space)
```xml
<?xml version="1.0" encoding="UTF-8"?>
<section>
--
    <p>foo</p>
    <p>bar</p>
--
</section>
```

**Comment by machakann** [comment]
* Remove
```xml
<?xml version="1.0" encoding="UTF-8"?>
<section>
    <p>foo</p>
    <p>bar</p>
</section>
```

**Comment by sudo-nice** [comment]
As for me, it seems more logical to remove empty lines. I can't think out, what these lines can be used for.
By the way, vim-sandwich appears to be a very handy plugin to me. Thank you very much for it! :star2:

**Comment by machakann** [comment]
I agree. I make it as removing empty lines and let's see if someone have any adverse comment. Please check the latest!

Thank you for your kind words. That really raises me up 😄

**Comment by sudo-nice** [comment]
Works fine for me, thank you!
