### ISSUE TITLE
Possible to keep cursor position after sdb/sdr/sda?

### ISSUE THREAD

**Issue by lervag** [machakann/vim-sandwich#3]
Hi! @maxfl [informed me](https://github.com/lervag/vimtex/issues/201) about your plugin, and I've tested it a little bit today. I think it looks very promising as a generalisation and improvement of the well known `surround.vim`, and I think I might make a permanent change.

I was wondering if it would be possible to keep the cursor position fixed while doing an add/delete/replace operation. I think that would make the operations slightly more intuitive (it sort of doesn't make sense that the cursor moves, does it?).

**Comment by machakann** [comment]
I really surprised! I welcome you, please try this if you are interested.

I'm slightly less confident whether I could get your point, but there is an local option to control cursor position after an action, named 'cursor'. The option can take several choices and an item 'keep' try to keep cursor position as possible. It can be used like this.
```vim
let g:sandwich#recipes = deepcopy(g:sandwich#default_recipes)
let g:sandwich#recipes += [{'buns': ['(', ')'], 'cursor': 'keep'}]
```
This is an example to keep cursor locally in each recipe, in this case cursor position is kept only for () pair.

Or user can simply change the default value of  'cursor' option.
```vim
call operator#sandwich#set('all', 'all', 'cursor', 'keep')
```
Add this line into your vimrc or just execute in command line. I think this is much easier to test.

Unfortunately, 'keep' is not valid on `.` command repeating at this moment. It is a bit difficult... If you like it, please tell me. I will try to think the way to realize.

**Comment by lervag** [comment]
Thanks, this works almost perfectly. As you say, 'keep' is not valid on `.`; if it is possible, then this would be a very nice feature if you find a way to make it work!

Again, thanks!

**Comment by machakann** [comment]
FYI: Not so elegant way, but the latest version can keep cursor position even after dot repeating, if user allow to map a function to `.` key.

If you are using other plugins which make a keymapping to `.` key, for example if you are using repeat.vim, then add the line into vimrc.
```vim
nmap . <Plug>(operator-sandwich-predot)<Plug>(RepeatDot)
```
Otherwise add the following line.
```vim
nmap . <Plug>(operator-sandwich-dot)
```

Please try if you are still interested, when you have free time.

**Comment by lervag** [comment]
It works well, thanks!
