### ISSUE TITLE
FR: An emmet-like behavior when adding/replacing tags

### ISSUE THREAD

**Issue by KabbAmine** [machakann/vim-sandwich#30]
A feature request here, I know that this not really what vim-sandwich should provide, but it will be great to have an emmet-like behavior when adding or replacing xml tags, at least only for classes and ids.

So for example having this:

```html
Foo bar
```

Using `sailt` (`il` in my config is for the whole line) with the following tag: `h1.title` will produce:

```html
<h1 class="title">Foo bar</h1>
```

Same thing goes for ids, so `h1#title` will produce:

```html
<h1 id="title">Foo bar</h1>
```

This behavior should also be applicable when replacing tags.

Is that hard to implement? Or maybe it is beyond the scope of the plugin?

**Comment by machakann** [comment]
Looks interesting. I'm not so familiar with Emmet, but unless it could be very complex, it is probably possible. Not all the Emmet functions might be supported, not sure at this moment.

Let me give it a try anyway, just as a experimental feature.

**Comment by KabbAmine** [comment]
The `element.class` and `element#id` syntaxes are enough IMO (If I remember well, surround also allows using them).

**Comment by machakann** [comment]
Hi, I hasten to add `element.class` and `element#id` expansion to **emmet-like** branch. Could you try if you have time? I will check more carefully later.

**Comment by KabbAmine** [comment]
Great work @machakann, from what I've tested the implementation works wonderfully well :+1:

**Comment by KabbAmine** [comment]
Some remarks if we want to improve the behavior.

----------------

Multiple classes should be joined.  
For example `tag.foo.bar` should produce:

```html
<tag class='foo bar'>content</tag>
```

instead of 

```html
<tag class='foo' class='bar'>content</tag>
```

-----------------

When combining classe(s) and id:

- `tag.foo#bar` produces `<tag class='foo' id='bar'>content</tag>` and that's correct.
- `tag.foo.foo2#bar` produces `<tag class='foo' class='foo' #bar>content</tag>`

**Comment by machakann** [comment]
OK, updated and those expressions are now supported.
In addition, the custom attributes is also available, for example `tag[attr=value]` is converted to `<tag attr="value">`.

**Comment by KabbAmine** [comment]
I've just tested now, and it works like a charm. You've really done a good job.

**Comment by machakann** [comment]
Merged! ㊗️

Thank you for your suggestion and comments!

**Comment by machakann** [comment]
- [ ] Update wiki.
