### ISSUE TITLE
Targets.vim: recorded vim macro inserts colons instead of **

### ISSUE THREAD

**Issue by kiryph** [machakann/vim-sandwich#32]
Consider following markdown file:

```
A markdown list

- Titles with Spaces, Date
- Titles with Spaces with different lengths, Date
- Titles with Spaces hjkl Date
- Titles with Spaces asdf and hjkl, Date
- Short title Date
```

I want to surround the titles with two stars to make them bold using vim-sandwich. I know there are more ways to do this. However, recording a vim-macro of the vim-sandwich **instant surround** command shows unexpected behaviour which might not be the intention of this plugin:

1. Move cursor to `Titles with Spaces` (cursor is over capital `T` of `Titles`)
2. `qq` starts recording macro
3. Execute surround command (using vim-surround mappings): `yst,i**<Enter>**<Enter>`
4. `q` stop recording macro
5. move cursor to next line
6. repeat macro with `@q`

Surprisingly colons instead of two stars are inserted to surround the next title and the cursor is moved to the beginning of the file which is also not part of the macro.

```
<CURSOR>A markdown list

- **Titles with Spaces**, Date
- :Titles with Spaces with different lengths:, Date
- Titles with Spaces hjkl, Date
- Titles with Spaces asdf and hjkl, Date
- Short title, Date
```

**NOTE**
For the record, dot-repeat works. However, in my case I want to do some edits in-between which override what is repeated with dot.  
In order to mitigate this issue for now, one can use capital `I` to **recall last surrounding**. When I want to run the macro with`@q`, I can press `yst,I`. However, this does not work when one of the edits between used vim-sandwich (https://github.com/machakann/vim-sandwich/wiki/Magic-characters#instant-surroundings).

**Comment by machakann** [comment]
Hi, just now I hasten to try the procedures but, unfortunately, I could not have reproduced. It is very strange that ':' is inserted instead, there should be some bug maybe... I will look into more carefully.

If you don't mind, could you tell me your operating system and which kind of environment you use vim, I mean using vim in a terminal emulator or using gvim?

**Comment by kiryph** [comment]
Thanks, for the feedback. After trying a minimal working example, the issue disappeared:

```viml
❯ cat mwe-vimrc
" invoke with
" $ vim -N -u ~/.vim/mwe-vimrc
runtime autoload/plug.vim
call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-repeat'
Plug 'vim-scripts/visualrepeat'
Plug 'machakann/vim-sandwich'
" Plug 'wellle/targets.vim'
call plug#end()

runtime macros/sandwich/keymap/surround.vim
call operator#sandwich#set('all', 'all', 'highlight', 0)
let g:operator#sandwich#timeoutlen = 0
runtime autoload/repeat.vim
nmap . <Plug>(operator-sandwich-predot)<Plug>(RepeatDot)
```

Uncommenting the line `Plug 'wellle/targets.vim'` and the issue is back. So it seems to be an
**incompatibility between sandwich.vim and targets.vim**.

If you know how to resolve this, I am happy to hear.

Right now, I'll leave it as it is, since I do not use vim-macros too extensively that it would bother me. If I want to edit a larger dataset, I simply temporarily disable `targets.vim`.

**Comment by machakann** [comment]
Thank you for your detailed report! That's really helpful, I have reproduced successfully! I will check the `targets.vim` to clarify what happened.

**Comment by kiryph** [comment]
Good to know that you could reproduce it!

I think it is a weird behavior: why the heck do colons show up?
Interestingly, if you do not use `operate till comma` (`t,`) but for instance `qqysiwi**<Enter>**<Enter**qn@q`, it works just fine

**Comment by machakann** [comment]
I found that I could reproduce only if `onoremap i* :` is executed, without `targets.vim`.
This is very strange. The `i*` should not interpreted as `:`, because after `t,` no longer in operator-pending mode.

It might be a bug of vim, I will ask others who are more familiar with vim source code.

**Comment by kiryph** [comment]
I am not sure whether following could be related to this issue:

I recently learned about macro ambiguity due to incorrectly separated series of sent keycodes by their timing. The plugin fixkey gives an example in the docs https://github.com/drmikehenry/vim-fixkey/blob/ce59fe84039941f0ce113ffea937a92ca495bba3/doc/fixkey.txt#L47-L66
However, I can reproduce the example only in vim not in macvim or neovim where my issue occurs.

**Comment by kiryph** [comment]
Removing `*` from the variable `g:targets_separators` of the plugin `targets.vim` resolves this issue! This can be done by putting following to the vimrc:

`let g:targets_separators = ', . ; : + - = ~ _ # / | \ & $'`

Default value is

`let g:targets_separators = ', . ; : + - = ~ _ * # / | \ & $'`

I think this removes the definiton of `onoremap i*` as you have pointed out.

However, I still do not understand why a colon is inserted and the cursor is moved to the beginning.

Following default of `targets.vim` should also be kept in mind `let g:targets_tagTrigger = 't'`.

**Comment by kiryph** [comment]
With the plugin `targets.vim` `:verbose map i*` returns
```
o  i*          * :<C-U>call targets#o('*ci', v:count1)<CR>
        Last set from ~/.vim/plugged/targets.vim/plugin/targets.vim
```

Instead of using the plugin `targets.vim` one can add create an own mapping, e.g.
```
onoremap i* h
```
This has the effect that simply an `h` is inserted.

**However, commenting `let g:operator#sandwich#timeoutlen = 0` in the `mwe-vimrc` resolves this issue in this case but not when using `targets.vim`.**

**Comment by machakann** [comment]
Yes, that's the point. Now I also found that the `:` in `{rhs}`

```
:<C-U>call targets#o('*ci', v:count1)<CR>
```

is inserted and the moiety moves the cursor, but anyway the mapping shouldn't expanded, as we type manually.
