### ISSUE TITLE
Would you consider adding textobjects ic/ac, ie/ae for tex?

### ISSUE THREAD

**Issue by kiryph** [machakann/vim-sandwich#35]
Consider following tex snippet
```tex
\begin{frame}
  \begin{center}
    \alert{\emph{emphasized text}}
  \end{center}
\end{frame}
```
Cursor is on `x`. Filetype is `tex`.

Since you have already added many rules for tex, many things I expect already work:

- `dsc` deletes the command and only `emphasized text` remains. Similarly, `dse` works for environment.
- `vabab` selects the curly brackets and I think afterwards the command

However, I miss something like `ac` to select the text and the command or `ae` to select a surrounding environment. As far as I understand `ab` considers all recipes. I miss more destinctive mappings.

See also my post here https://github.com/lervag/vimtex/issues/687#issuecomment-280662192 and in general the textobject functionality of vimtex. Right now I use vimtex for this, however, I really like the capability of extending a selection via `vabab` which vimtex does not support.

**Comment by machakann** [comment]
I'm torn whether I should or not. Although it would be helpful definitely, but appending default keymappings is probably dangerous. It is really easy to conflict with another setting/plugin, and it might be confusing that a general plugin defines filetype-specific keymappings. I'd rather like to be discreet to append keymappings.

If you are sure `ae` and `ac` are safe, how about putting a file `.vim/after/ftplugin/tex.vim` like:

```vim
omap <buffer> ie <Plug>(textobj-sandwich-query-i)e
xmap <buffer> ie <Plug>(textobj-sandwich-query-i)e
omap <buffer> ae <Plug>(textobj-sandwich-query-a)e
xmap <buffer> ae <Plug>(textobj-sandwich-query-a)e
omap <buffer> ic <Plug>(textobj-sandwich-query-i)c
xmap <buffer> ic <Plug>(textobj-sandwich-query-i)c
omap <buffer> ac <Plug>(textobj-sandwich-query-a)c
xmap <buffer> ac <Plug>(textobj-sandwich-query-a)c
```

**Comment by kiryph** [comment]
First of all it is great to see how easy one can add this functionality to sandwich. I will add them to my local config. Thanks for this.

I understand your point, that filetype specific mappings in a general purpose plugin might be surprising and can lead to conflicts. In this case there would be already a conflict with vimtex and a user should be made aware of this conflict and have the possibility to choose between them.

However, I think also filetype-specific rules can be unintuitive. It should be documented that these textobjects only apply to tex files as the provided rules and how he can assure they are defined last.

If you do not like to enable them by default, you can either add a boolean variable or add these mappings to the documentation and leave it to the user to activate or add them to his own config.
