### ISSUE TITLE
Extend tex recipe for delimiters for \lVert, \lceil, \lfloor and size specifiers

### ISSUE THREAD

**Issue by kiryph** [machakann/vim-sandwich#36]
I have added following line to my `~/.vim/after/ftplugin/tex.vim` to extend the recipe defined in `ftplugin/initex/sandwich.vim` with input `ma`:
```viml
let b:sandwich_recipes[26].buns = [
  \ '\m\(\\left\|\\big\|\\Big\|\\bigg\|\\Bigg\)\?\((\|\[\||\|\\{\|\\langle\|\\lvert\|\\lVert\|\\lfloor\|\\lceil\|\.\)',
  \ '\m\(\\right\|\\big\|\\Big\|\\bigg\|\\Bigg\)\?\()\|]\||\|\\}\|\\rangle\|\\rvert\|\\rVert\|\\rfloor\|\\rceil\|\.\)'
  \ ]
```

I want to extend it to recognize `\lVert`, `\lceil`, `\lfloor` and alternative size specifier `\big, \Big, \bigg, \Bigg`. Also the recipe should match without a size specifier at all.

However, it does not work for `\Big( a+b \Big)`. Using surround style delete command `dsma`, nothing happens. Can you help me to identify the issue with my regex?

I have made another observation with the original recipe: It contains `\[` for the left and `]` for the right. Is this correct? Which regex mode is used by default (verymagic, magic, nomagic, very nomagic/literal?

**Comment by machakann** [comment]
Thank you. In fact, I haven't tested well, and yes it looks slightly strange. Let me think...

**Comment by machakann** [comment]
Your regex pattern seems to work fine for me with `\Big( a+b \Big)`, but had a problem with `\bigg( a+b \bigg)`. Probably `\\big` matches before `\\bigg` in the grouping.

**Comment by machakann** [comment]
Updated. I modified the regex a bit and set 'nesting' option as 0, because the pairs like "\big|" has a problem. When 'nesting' equals 1, vim-sandwich cannot work if former and latter surrounds are same. I may work on the problem for future.

```vim
    {
\   'buns'    : [
\                 '\m\C\%(\\left\|\\[Bb]igg\?l\?\)\?\%([[(|.]\|\\{\|\\langle\|\\lVert\|\\lvert\|\\lceil\|\\lfloor\)',
\                 '\m\C\%(\\right\|\\[Bb]igg\?r\?\)\?\%([])|.]\|\\}\|\\rangle\|\\rVert\|\\rvert\|\\rceil\|\\rfloor\)'
\               ],
\   'filetype': ['initex', 'plaintex', 'tex'],
\   'kind'    : ['delete', 'replace', 'auto', 'query'],
\   'regex'   : 1,
\   'nesting' : 0,
\   'input'   : ['ma'],
\   'indentkeys-' : '{,},0{,0}',
\   'autoindent' : 0,
\   },
```

**Comment by kiryph** [comment]
Thanks for the update. It looks good as far as I have checked.

There is one thing I really like to have: enabled nesting. That's the reason I want to use your plugin instead of vimtex's builtin delimiter support. I think it is totally understandable that delimiters which look identical for left and right cannot be associated to which nesting level they belong. Consider this `\bigg| a+b \bigg| c+d \bigg| + e \bigg|`. A human would consider `c+d` not within single bars. But when the cusor is on `c+d`, I would suspect that sandwich.vim considers `c+d` as surrounded by delimiters.
To avoid this a user should use either `\lvert`/`\rvert` instead of `|`. And for `\big.` one should use `\bigl.`/`\bigr`.

I think it is possible to write a second regex which only works for uniquely identifed delimiters (whether left or right) and enable nesting for this.

What do you think about this?

I would prefer to use this one.

I already use the plugin https://github.com/bootleq/vim-cycle with following setting for tex files

```viml
" requires amsmath for `Vert` and `vert`
let g:cycle_default_groups_for_tex = [
        \   [['(:)', '[:]', '\{:\}', '\lvert :\rvert', '\lVert :\rVert', '\lfloor :\rfloor', '\lceil :\rceil', '\langle :\rangle'], 'sub_pairs', 'hard_case', 'match_case'],
        \   [['\big(:\big)', '\Big(:\Big)', '\bigg(:\bigg)', '\Bigg(:\Bigg)'], 'sub_pairs', 'hard_case', 'match_case'],
        \   [['\big[:\big]', '\Big[:\Big]', '\bigg[:\bigg]', '\Bigg[:\Bigg]'], 'sub_pairs', 'hard_case', 'match_case'],
        \   [['\big\{:\big\}', '\Big\{:\Big\}', '\bigg\{:\bigg\}', '\Bigg\{:\Bigg\}'], 'sub_pairs', 'hard_case', 'match_case'],
        \   [['\big\l:\big\r', '\Big\l:\Big\r', '\bigg\l:\bigg\r', '\Bigg\l:\Bigg\r'], 'sub_pairs', 'hard_case', 'match_case'],
        \   [['\big', '\Big', '\bigg', '\Bigg'], 'hard_case', 'match_case'],
        \ ]
```

which allows me to use `ctrl-a/x` to cycle through delimiter sizes or delimiter types. However, this already enforces me to use uniquely identifed delimiters (whether left or right) (for details see https://github.com/bootleq/vim-cycle/issues/5).

**Comment by machakann** [comment]
Oh, I see. That makes sense. OK, I will work on enabling nesting. Wait a few days, please.

**Comment by machakann** [comment]
Updated, but it might not be perfect yet. Wait a little more, let me think...

**Comment by machakann** [comment]
By the way, I would like to ask, is it possible or rather popular to write these surrounding pairs like `\big( \big)` over multiple lines?

```tex
\big( a+b+     ...
+y+z \big)
```

If not, I will set `'expand_range'` option as 0 to search only in the current line. It will make safer. I'm slightly afraid to delete an unintended pair. (And it will reduce computational resource required to give better response.) Do you have any idea?

**Comment by kiryph** [comment]
It is possible to write them over multiple lines. People who write code with fixed linewidth will do this more often. I would suspect that someone who writes her/his code with softwrapping would not do it which, however, is not recommended e.g. by https://en.wikibooks.org/wiki/LaTeX/Collaborative_Writing_of_LaTeX_Documents.

I have compared to the textobject of vimtex (`id`/`ad`): this allows to have them on separate lines.

If I would loose multi-line support in order to get nesting support, I would prefer to have multi-line support. How bad is the response?

**Comment by machakann** [comment]
Thank you. It is still ok, probably very rare to be heavy and, anyway, `g:textobj#sandwich#stimeoutlen` should be the upperlimit.

I updated just now. The handling of `\big.` and `\big|` are somehow difficult but it seems to work well in many cases.

**Comment by kiryph** [comment]
I can confirm that incremental selection via `vadadad` works for
```tex
  \big. a+b+    \left( \lVert CURSOR+d \rVert \right)
  +y+z \big|
```
with following additional configuration
```viml
let b:sandwich_recipes[26].input = ['ma', 'd']
omap <buffer> id <Plug>(textobj-sandwich-query-i)d
xmap <buffer> id <Plug>(textobj-sandwich-query-i)d
omap <buffer> ad <Plug>(textobj-sandwich-query-a)d
xmap <buffer> ad <Plug>(textobj-sandwich-query-a)d
```

However, I miss matching of simple parenthesis
```tex
  \left( -1 (a+b) \right)
```
I can't select with `vad` `(a+b)`.

Thanks for your effort 👍 .

**Comment by machakann** [comment]
I missed the simplest ones.
