### ISSUE TITLE
Minor error in after/ftplugin/initex.vim

### ISSUE THREAD

**Issue by lervag** [machakann/vim-sandwich#37]
Hi. I just noticed there is a minor error in "after/ftplugin/initex.vim". At the bottom, you have:

```vim
if !exists('b:undo_ftplugin')
  let b:undo_ftplugin = ''
endif
let b:undo_ftplugin .= ' | unlet b:did_sandwich_initex_ftplugin | call sandwich#util#ftrevert("initex")'
```

However, it should rather be

```vim
if !exists('b:undo_ftplugin')
  let b:undo_ftplugin = ''
else
  let b:undo_ftplugin .= ' | '
endif
let b:undo_ftplugin .= 'unlet b:did_sandwich_initex_ftplugin | call sandwich#util#ftrevert("initex")'
```

The reason is that the current version will start the `b:undo_ftplugin` variable with `|` if the variable is empty to begin with. This results in echoing the current line when the undo is performed.

**Comment by machakann** [comment]
Thank you for reporting as an issue!

Yes, I believe that is the best way to do. However the default tex filetype plugin `$VIMTUNTIME/ftplugin/initex.vim` overwrites b:undo_ftplugin focibly at L19.

```tex

let b:undo_ftplugin = "setl com< cms< define< include< sua<"

```

Thus, if  `vim-sandwich/ftplugin/sandwich/initex.vim` was loaded earlier than `$VIMRUNTIME/ftplugin/initex.vim`, then it will be overwritten. At this moment, I only have the workaround to use `after/*` path. I will looking for the response of 09b982c34e7a0228e7f93eeaeaa05564b06ebe10 in lervag/vimtex#695.

**Comment by lervag** [comment]
Ah, I think I was not quite clear. In my particular case, `b:undo_ftplugin` is _not_ overwritten. Instead, `initex.vim` is never loaded (because `vimtex` is loaded instead), and so `vim-sandwich` sets the variable to:

```
echo b:undo_ftplugin
=> ' | unlet b:did_sandwich_initex_ftplugin | call sandwich#util#ftrevert("initex")'
```
The point here is that the initial ` |` should not be included if `b:undo_ftplugin` is empty.

**Comment by machakann** [comment]
Hi, sorry for my late response. I am ashamed but I've forgotten to push completely. Now I include the fix. Thanks!

**Comment by lervag** [comment]
Thanks! And no problem :)
