### ISSUE TITLE
Repeat after `sdb` is not silent

### ISSUE THREAD

**Issue by lervag** [machakann/vim-sandwich#4]
Hi. If I first do `sdb`, then repeat it with `.`, then the following is printed to the status: `call textobj#sandwich#select()`.

This might also be true for other operators, but it goes away after a very short time.

**Comment by machakann** [comment]
I see. This is probably in the specification of vim. I guess, and as you said,  it is common in all user-defined textobjects. So unfortunately I don't know the way not to display, however I can flash it within a short time. Please bear with it.

**Comment by machakann** [comment]
OK, implemented in the latest commit 6907f4719e707254553c5c62cc2c2f1803c4e5ce. Please try.

**Comment by lervag** [comment]
Perfect! Thanks!
