### ISSUE TITLE
Can't delete or replace the double quotes surrounding

### ISSUE THREAD

**Issue by sudo-nice** [machakann/vim-sandwich#40]
Hello, here are the steps to reproduce:
1. Open a new file and type `"foo"`
2. While being inside "foo", try to delete the double quotes (`sd"`) or replace it with something different (`sr"*`). These two attempts are failed for me. Can you reproduce?

**Comment by machakann** [comment]
Thank you! I reproduced. `sdb` works but `sd"` doesn't. It seems very strange. I will check!

**Comment by sudo-nice** [comment]
It works agan. Thank you!
