### ISSUE TITLE
Whitespace sensitive features of surround.vim for opening delimiters

### ISSUE THREAD

**Issue by kiryph** [machakann/vim-sandwich#44]
I miss following features from `vim-surround` in `macros/sandwich/keymap/surround.vim`:

`:h surround-targets`
> If the opening mark is used, **contained whitespace is also trimmed**. 

This has following effect: pressing `ds(` for `( a + b )` you get `a+b`. But with sandwich the surrounding whitespace is retained `␣a+b␣`. `ds)`  works the same for vim-surround and vim-sandwich. The same applies to `[`, `{`, and `<`.

`:h surround-replacements`
> If either ), }, ], or > is used, the text is wrapped in the appropriate pair
of characters.  Similar behavior can be found with (, {, and [ (but not <),
**which append an additional space to the inside**.

This has following effect: pressing `ysiw(` for `a + b` you get `( a + b )`. But with sandwich no space is inserted `(a+b)`. `ysiw)`  works the same for vim-surround and vim-sandwich. The same applies to `[` and `{`.

**Comment by machakann** [comment]
This is actually intended. When I introduced the `vim-surround` keymapping, I thought about the spaces inside baraces, but it has been unexpected behavior for me and not many objections at that time, thus I dropped the features intentionally as same as vim-sandwich's default.

So, at this moment I want users to deal with it by themselves. Add the lines after `runtime` command.

```vim
runtime macros/sandwich/keymap/surround.vim
let g:sandwich#recipes += [
      \   {'buns': ['{ ', ' }'], 'nesting': 1, 'match_syntax': 1, 'kind': ['add', 'replace'], 'action': ['add'], 'input': ['{']},
      \   {'buns': ['[ ', ' ]'], 'nesting': 1, 'match_syntax': 1, 'kind': ['add', 'replace'], 'action': ['add'], 'input': ['[']},
      \   {'buns': ['( ', ' )'], 'nesting': 1, 'match_syntax': 1, 'kind': ['add', 'replace'], 'action': ['add'], 'input': ['(']},
      \   {'buns': ['{\s*', '\s*}'],   'nesting': 1, 'regex': 1, 'match_syntax': 1, 'kind': ['delete', 'replace', 'textobj'], 'action': ['delete'], 'input': ['{']},
      \   {'buns': ['\[\s*', '\s*\]'], 'nesting': 1, 'regex': 1, 'match_syntax': 1, 'kind': ['delete', 'replace', 'textobj'], 'action': ['delete'], 'input': ['[']},
      \   {'buns': ['(\s*', '\s*)'],   'nesting': 1, 'regex': 1, 'match_syntax': 1, 'kind': ['delete', 'replace', 'textobj'], 'action': ['delete'], 'input': ['(']},
      \ ]
```

... However, I should write down it somewhere in docs. I will. Please keep this issue opened, I would like to know any other comments on this.

**Comment by kiryph** [comment]
Thanks for your answer and the solution.

This is really great that `vim-sandwich` can be customized this easily. Much better than `vim-surround` where everything is hard-coded.

To be honest, when I started with `vim-surround`, I didn't read the docs properly and the behavior of the left vs. right delimiters were also unexpected for me. Having the same behavior for left and right delmiter is IMHO more beginner friendly (https://vi.stackexchange.com/questions/5492/why-does-vim-surround-add-spaces-in-this-example). I and apparently others were also stumbling about the asymmetry of `<` and `>` (https://vi.stackexchange.com/questions/12130/replace-surrounding-quotes-for). There are quite a few subtleties in `vim-surround` which are not obvious and make the plugin a little bit more difficult to use. The user should read carefully `:h surround-targets` and `:h surround-replacements`.
