### ISSUE TITLE
Delete or replace surrounding whitespace

### ISSUE THREAD

**Issue by kiryph** [machakann/vim-sandwich#45]
`vim-surround` has recently added an undocumented feature to delete surrounding spaces with `ds<Space><Space>` (https://github.com/tpope/vim-surround/commit/e38dea39723c49caa7700f1b8904314e07a82a65).

Woud you consider adding a similar feature to `vim-sandwich`?

The `target` can be `\s*` and the `replacement` a single `<space>`.

This could also be helpful in situations where people delete a surrounding parentheses and notice there is unwanted whitespace left (see #44 ).

This is similar to `<CR>` where I am wondering whether deletion/replacement should not only delete a single line but all contiguous empty lines.

**Comment by machakann** [comment]
Even now `vim-sandwich` can add/delete spaces, but what you mean is, for example, `sr<space><space>` (or might be `cs<space><space>`) does this:

```
␣␣␣foo␣␣␣   →   ␣foo␣
```

Isn't it? (Delete multiple spaces but add a space)

**Comment by machakann** [comment]
It sounds useful enough, but might be surprising at bit. Let me think a little more.

**Comment by kiryph** [comment]
Yes, I meant several spaces or tabs as you have shown.

**Comment by machakann** [comment]
Hi, finally I added the recipe to delete successive spaces! Probably it works as you expected.

As for the `<CR>`, I tried but it is sometimes difficult to recognize what happened especially in a narrow console window. It is possibly dangerous depending on use cases, so I want to skip including it in default recipes. Users can add it by themselves like this:

```vim
let g:sandwich#recipes = [
      \   {'buns': ['\%(^$\)\+', '\%(^$\)\+'], 'regex': 1, 'kind': ['delete', 'replace', 'query'], 'input': ["\<CR>"]},
      \ ]
```

**Comment by kiryph** [comment]
Thanks for your update. deleting surrounding whitespace works.

However, your suggestion for `<CR>` does not work. Have you checked it on your system?

**Comment by machakann** [comment]
Oops, sorry now I've got what happened. It highlights empty lines but not deleted. I will check it again.

**Comment by kiryph** [comment]
Nope, no change at all. My minimal vimrc looks like this:
```viml
" invoke with
" $ vim -u ~/.vim/mwe-vimrc
set nocompatible
filetype plugin indent on
let g:dein#types#git#clone_depth = 1
set runtimepath+=~/.cache/vim/dein/repos/github.com/Shougo/dein.vim
if dein#load_state('~/.cache/vim/dein')
  call dein#begin('~/.cache/vim/dein')
  call dein#add('Shougo/dein.vim')
  call dein#add('machakann/vim-sandwich')
  call dein#end()
  call dein#save_state()
endif



let g:sandwich#recipes = deepcopy(g:sandwich#default_recipes)
let g:sandwich#recipes[2]= {'buns': ['\%(^$\)\+', '\%(^$\)\+'], 'regex': 1, 'kind': ['delete', 'replace', 'query'], 'input': ["\<CR>"]}

```

`sd<cr>` on `deepcopy` does not do anything.

**Comment by machakann** [comment]
In principle, `sd` and `sr` fails if either opening or closing brace was not found. Thus, in this case, probably you need more than one empty line at the end of the buffer, though it does not work correctly now.

**Comment by kiryph** [comment]
Well, my original issue regarding spaces is already solved and I don't feel strongly about having this for `<CR>` except for consistency.
 
Regarding superfluous empty lines one can resort to `:h collapse` and questions like https://unix.stackexchange.com/questions/12812/replacing-multiple-blank-lines-with-a-single-blank-line-in-vim-sed or use auto styling tools such as https://github.com/sbdchd/neoformat or https://github.com/Chiel92/vim-autoformat. Therefore I close this issue.

**Comment by machakann** [comment]
Thank you for your report!
