### ISSUE TITLE
Tags with attributes on separate lines.

### ISSUE THREAD

**Issue by c0r73x** [machakann/vim-sandwich#46]
Hi

I found a problem in autoload/sandwich/magicchar/t.vim on line 313 you have:
```vim
    let pat = a:kind ==# 'i' ? '<\a[^[:blank:]>/]*\zs.' : '<\zs\a[^[:blank:]>/]*'
```
This should be changed to:
```vim
    let pat = a:kind ==# 'i' ? '<\a[^[:blank:]>/]*\zs\_.' : '<\zs\a[^[:blank:]>/]*'
```

To allow replace on tags that have attributes on new lines, for example:
```html
<div
    id='foo'
    class='bar'
>
   foobar
</div>
```

**Comment by machakann** [comment]
Thank you for the detailed report! Please test the latest version.

**Comment by c0r73x** [comment]
Perfect :+1:, tyvm :smile:
