### ISSUE TITLE
Is is possible to disable the animation/preview/visual highlight of the operation?

### ISSUE THREAD

**Issue by joereynolds** [machakann/vim-sandwich#48]
I've got a 9000 line csv file which I want to surround the first column in `(`

i.e. from this

```
931832,25/08/2018,1159
931832,01/09/2018,832
931832,08/09/2018,832
931832,15/09/2018,791
931832,22/09/2018,720
...9000 more lines...
```

To this

```
(931832),25/08/2018,1159
(931832),01/09/2018,832
(931832),08/09/2018,832
(931832),15/09/2018,791
(931832),22/09/2018,720
...9000 more lines...
```

I've got one way of doing it (operating per line) but it's very slow as it previews each change. I would just like it to run it all and not show each change as it's doing it (though I suspect this is at the very core of vim-sandwich and maybe not trivial?)

For the record, the command I was using was basically

Visual block on the first record `ctrl+v`
go to the end of the file `G`
Operate on all of them with a `normal` command on a visual selection
`:'<,'>norm saiw(`

I suspect that it's my use of sandwich that is incorrect here and that there's probably a better way of doing this.

Thoughts?
Thanks!

**Comment by machakann** [comment]
Hi, if you want to disable the highlight feature, add the line in your vimrc.
```vim
operator#sandwich#set('all', 'all', 'highlight', 0)
```

Or if you want to turn off temporary, you may use a command like this:
```vim
let s:sandwich_highlight_on = 1
function! s:sandwich_highlight_toggle() abort
  if s:sandwich_highlight_on
    call operator#sandwich#set('all', 'all', 'highlight', 0)
    let s:sandwich_highlight_on = 0
    echo 'sandwich: highlight OFF'
  else
    call operator#sandwich#set('all', 'all', 'highlight', 1)
    let s:sandwich_highlight_on = 1
    echo 'sandwich: highlight ON'
  endif
endfunction
command! -nargs=0 SandwichHighlightToggle call s:sandwich_highlight_toggle()
```

If the highlight is turned off, the display would not be redrawn in an operation. In my PC, the time to finish the example could be about 80% (~100s to ~80s) after turning off the highlight.

Honestly, the sandwich would be slower than competitors (surround.vim, operator-surround) to support the bunch of features, though I didn't examine. In your case, if the first column has a fixed width, the use of blockwise-visual mode may help. For example;  
  
Visual block on the first record *ctrl+v*
go to the end of the file *G*
go to the right-end of the columns *e*
press *sa(*
  
It would be faster, although the use of *I* and *A* in blockwise-visual mode is much more faster.
  
Visual block on the first record *ctrl+v*
go to the end of the file *G*
insert a open paren *I(<esc>*
go to the head of the file *gg*
go to the right-end of the column *e*
Visual block on the first record *ctrl+v*
go to the end of the file *G*
insert a close paren *A)<esc>*

Forgive me if you knew it.

**Comment by joereynolds** [comment]
Hi @machakann,

I'll try those now, feel free to close this, I was just asking a question, thanks for the indepth help! :D

**Comment by joereynolds** [comment]
I had no idea `A` could be used like that, I thought it only appended at the end of a line :O

**Comment by machakann** [comment]
I'm glad I could help.
It may not be intuitive but very useful! Pushing `$` key before `A`, then it works as you expected, FYI.
