### ISSUE TITLE
Cursor moved to tail during operator change/add

### ISSUE THREAD

**Issue by lervag** [machakann/vim-sandwich#5]
During `sa...` or `sr...`, the cursor is moved to the tail of the text object. I was thinking it could look better if the cursor was "disabled" instead, so that only the edge was highlighted. Please see screenshot.

![screen1](https://cloud.githubusercontent.com/assets/998898/8618690/ca0725f4-2710-11e5-92ef-4478e4184857.png)

**Comment by machakann** [comment]
I see. I've got the point, but this is in specification of vim editor. All operators including built-in operators like d, y, c are also same.  However it might be possible, let me think. If possible, I will implement it as optional feature.

**Comment by lervag** [comment]
Great! I am thinking it might be possible by temporarily changing the Cursor highlighting, or alternatively changing the `guicursor` option (for gui only) and/or the `t_SI` or `t_EI` for terminals.

**Comment by machakann** [comment]
Yes, that method is the very I'm thinking. It should be possible.

**Comment by machakann** [comment]
umm... `'a'` mode of `guicursor` option seems slightly weird, but anyway the feature is implemented at 3ddc4ee2f7ae660712826ddf54b8966f997b8597. If any problem, please tell me!

To activate the feature, add the following line into your vimrc.
```vim
let g:operator#sandwich#hide_cursor = 1
```

**Comment by machakann** [comment]
Finally I changed my mind. I set the behavior as default (83cda7a59bd0fd6ae97847e02f4ffcbae8b3e129), not as an optional feature. Because it looks great :)
Thank you for your idea!

**Comment by lervag** [comment]
Thanks, this is exactly what I wanted and it works very well! I'm happy that you liked the idea. Thanks for developing this great plugin!
