### ISSUE TITLE
Bug: recording to a register with sd (sandwich-delete)

### ISSUE THREAD

**Issue by AssailantLF** [machakann/vim-sandwich#50]
More details and how to reproduce: 

1. Try recording into any register via `q`

2. Delete surroundings via `sandwich-delete`

3. either of these:

    - Enter insert mode in any way

    - Use `sandwich-add`

    - Use `sandwich-delete`

    - Use `sandwich-replace`

4. Finish the recording

5. Move back to where you started the recording

6. Attempt to play back the recording. 

Some kind of error occurs when it tries to play back around the part that was recorded at step 3.

In my tests with both my vimrc and with vanilla vim+sandwich, and with or without the surround-style bindings, neither `sandwich-add` nor `sandwich-replace` have this issue.

**Comment by machakann** [comment]
I'm not sure whether only it was the reason or not, but I just found a small problem in sandwich-delete and fixed it. Could you test and see what happens?

**Comment by AssailantLF** [comment]
That seems to have fixed it, thanks!
