### ISSUE TITLE
Bug: runtime macros/.../surround.vim doesn't work at all

### ISSUE THREAD

**Issue by AssailantLF** [machakann/vim-sandwich#51]
When `runtime macros/sandwich/keymap/surround.vim` is present in your vimrc, it fails to execute properly at startup due to the sort of load order Vim goes through. I think that `vim-sandwich` isn't available when the vimrc is read, so the `surround.vim` file never loads. I tried working around this via `au! VimEnter *`, which sort of works, but since it executes the script after `sandwich` has already loaded, the variable options don't work, leaving all of the original bindings/operators/textobjects still intact along with the surround bindings.

A simple fix I propose is to remove the first 3 lines of `macros/.../surround.vim`, ask the user to instead put those in their vimrc, along with `VimEnter` to execute the script properly:

    let g:sandwich_no_default_key_mappings = 1
    let g:operator_sandwich_no_default_key_mappings = 1
    let g:textobj_sandwich_no_default_key_mappings = 1
    augroup SandwichSurround
      au! VimEnter * runtime macros/sandwich/keymap/surround.vim
    augroup END

This works fine for me so far, gives the user more choice over options (e.g. I don't have the textobj line in my vimrc, because I still like them). Maybe you have a simpler or better solution tho :P

**Comment by machakann** [comment]
Ah... It comes to a very complicated problem sometimes. But probably ":runtime command doesn't work properly" means the vim-sandwich is not in your `'runtimepath'`. I guess you're using a kind of package manager, like [Vundle](https://github.com/VundleVim/Vundle.vim), [plug](https://github.com/junegunn/vim-plug) or [neobundle](https://github.com/Shougo/neobundle.vim). If so, they add your registered plugins in rutimepath when `vundle#end()`/`plug#end()`/`neobundle#end()` is called. Thus vim-sandwich (and others) doesn't appear in your environment until then.

In this case (sorry if not), you have several choices.

---

1. Move the `:runtime` command line after calling `vundle#end()`/`plug#end()`/`neobundle#end()`.

```vim
vundle#begin()
~~~
Plugin 'machakann/vim-sandwich'
~~~
vundle#end()
runtime macros/sandwich/keymap/surround.vim
```

---

2. Use `:source` command instead.

```vim
" runtime macros/sandwich/keymap/surround.vim
source {full/path/to}/macros/sandwich/keymap/surround.vim
```

Please change {full/path/to} part for your environment.

---

3. Use autocommand to delay the loading as you did.

---

**Comment by AssailantLF** [comment]
I am indeed using vim-plug. I'm not entirely familiar with the runtime, but with your explanation, I fully understand and am content with my workaround.

Thanks for the help, and the awesome plugin. Perhaps those solutions are worth mentioning in the docs or wiki somewhere, since plugin managers are pretty prevalent.

**Comment by machakann** [comment]
Yes, indeed. Those package managers are widely used now. I will work on it on the weekend. It may help others a lot, Thanks!
