### ISSUE TITLE
Html tag surrounding doesn't surround whole line when it is not indented

### ISSUE THREAD

**Issue by jeromedalbert** [machakann/vim-sandwich#52]
### Steps to reproduce

1. Put the following text in an html buffer:
```
        <select class="custom-select">
          <option selected>Open this select menu</option>
          <option value="1">One</option>
          <option value="2">Two</option>
          <option value="3">Three</option>

30 min later
1 hour later 
3 hours later
6 hours later
12 hours later
1 day later
3 days later
7 days later
14 days later

        </select>
```

2. Move the cursor to the beginning of the `30 min later` line.
3. Type `yss` (I am using vim-surround mappings), then `t`, then `option`, then press enter.

### Actual

The result is an indented `<option>30</option> min later` line, as shown below:

![sandwich_bug](https://user-images.githubusercontent.com/236461/32119219-68102ad2-bb09-11e7-9dc8-13b51db53888.gif)

### Expected

The result should be `<option>30 min later</option>`.
I am not sure what to expect for the indentation part (cf GIF above), but my best guess is that the line should not be indented either.

### Additional comments

Incidentally, I have disabled highlighting with `call operator#sandwich#set('all', 'all', 'highlight', 0)` in my config. But the line is still highlighted for tag manipulation (cf GIF above). I would expect it not to be highlighted too.

**Comment by machakann** [comment]
Thank you! Both of them were bugs. I pushed the fixes for them, could you update and test the latest?

**Comment by machakann** [comment]
As for the indentation, since vim-sandwich first tries to edit as if you typed, it does not suppress Vim's default auto-indent. Probably, if you type the `<option>` then you will see the same result. However, if you don't like it, you can set "autoindent" option to 0.

```vim
call operator#sandwich#set('all', 'all', 'autoindent', 0)
```

**Comment by jeromedalbert** [comment]
Everything works great, thank you @machakann for this nice plugin!

As for auto-indent, if this is mirroring Vim default behavior, then I will keep it this way.
