### ISSUE TITLE
`:set expandtab` affects surrounding with single space

### ISSUE THREAD

**Issue by sudo-nice** [machakann/vim-sandwich#53]
Hello, here is a tiny issue. Steps to reproduce:

1. Open an empty buffer.
2. Type: `123`.
3. Place the cursor on `2`.
4. Hit: <kbd>vS[space]</kbd> or <kbd>ysl[space]</kbd> (with surround-like macro).
5. The result depends on the current `expandtab` setting:
  - with `set expandtab` I will get `1  23`
  - with `set noexpandtab` I will get `1 2 3`

Every subsequent change of this setting, affects vim-sandwich accordingly.

**Comment by machakann** [comment]
Thank you! I may degrade it in a recent commit (15ff877b92b3060cc7b1cfef00a23f192eccc9b9). Probably it is now fixed. Could you test it?

**Comment by sudo-nice** [comment]
Great, thank you!
