### ISSUE TITLE
textobj-sandwich-query: check for sandwiches after default vim text-objects

### ISSUE THREAD

**Issue by albertfgu** [machakann/vim-sandwich#56]
I would like to map the sandwich query textobjects to just 'i' and 'a', e.g. `xmap i  <Plug>(textobj-sandwich-query-i)`. This way a command just as `di(` is consistent between both the sandwich-defined textobject and the default vim textobject, and it saves a lot of keystrokes.

However, this breaks when attempting to use the default textobjects such as `iw` (sandwich will search for surrounding 'w' characters). Ideally, when parsing a textobject it should first check for default vim textobjects before using the query. Is there any way to make this work?

**Comment by albertfgu** [comment]
I also noticed related problems because of these same character sandwiches. For example, in Latex, sandwich defines the very useful \[ and \{ sandwich objects. Therefore, when trying to match on surrounding '\' characters (e.g. `sr\|`), it doesn't work because it seems that it is waiting to resolve the '\' in case the next character in the query is '[' or '{'.

If I may make a suggestion, the fact that the query textobjects default to "same character user input" behavior seems to be related to both issues. Perhaps this behavior could be toggled off? Alternatively, make this the default, but toggle it off if mappings for the `textobj-sandwich-literal-query` objects are defined. This way the behaviour of all possible textobjects should be unambiguous.

**Comment by machakann** [comment]
You can do like this:

```vim
let g:textobj#sandwich#recipes = [
  \   {'external': ['iw', 'aw'], 'noremap': 0, 'input': ['w']},
  \   {'external': ['iW', 'aW'], 'noremap': 0, 'input': ['W']},
  \   {'external': ['is', 'as'], 'noremap': 0, 'input': ['s']},
  \   {'external': ['iS', 'aS'], 'noremap': 0, 'input': ['S']},
  \   {'external': ['ip', 'ap'], 'noremap': 0, 'input': ['p']},
  \   {'external': ['iP', 'aP'], 'noremap': 0, 'input': ['P']},
  \   {'external': ['i[', 'a['], 'noremap': 0, 'input': ['[']},
  \   {'external': ['i]', 'a]'], 'noremap': 0, 'input': [']']},
  \   {'external': ['i(', 'a('], 'noremap': 0, 'input': ['(']},
  \   {'external': ['i)', 'a)'], 'noremap': 0, 'input': [')']},
  \   {'external': ['ib', 'ab'], 'noremap': 0, 'input': ['b']},
  \   {'external': ['i<', 'a<'], 'noremap': 0, 'input': ['<']},
  \   {'external': ['i>', 'a>'], 'noremap': 0, 'input': ['>']},
  \   {'external': ['it', 'at'], 'noremap': 0, 'input': ['t']},
  \   {'external': ['i{', 'a{'], 'noremap': 0, 'input': ['{']},
  \   {'external': ['i}', 'a}'], 'noremap': 0, 'input': ['}']},
  \   {'external': ['iB', 'aB'], 'noremap': 0, 'input': ['B']},
  \   {'external': ['i"', 'a"'], 'noremap': 0, 'input': ['"']},
  \   {'external': ["i'", "a'"], 'noremap': 0, 'input': ['''']},
  \   {'external': ['i`', 'a`'], 'noremap': 0, 'input': ['`']},
  \ ]
```

In fact, you can also do like this:

```vim
omap i <Plug>(textobj-sandwich-query-i)
xmap i <Plug>(textobj-sandwich-query-i)
onoremap iw iw
xnoremap iw iw
...
```

However, this would overwrite filetype-specific recipes if exists. Thus the above one would be better.

**Comment by machakann** [comment]
The keymapping like `<Plug>(textobj-sandwich-query-i)` cannot recognize its `{lhs}`, for example `i` in `xmap i <Plug>(textobj-sandwich-query-i)`, for sure. Therefore it is impossible to check the built-in textobjects with 100 % confidence. 

I think the above settings works well.

**Comment by machakann** [comment]
As for the recipes with overlapped `input`, for example, `\` and `\[`, if you wait some time or press a key other than `[` after `\` then the recipe of `\` will be used, as same as the native behavior of vim. It might be helpful if you set `g:operator#sandwich#timeoutlen` smaller, it makes timeout faster. The default value is same as the `'timeoutlen'` option, probably 1000 ms.

```vim
let g:operator#sandwich#timeoutlen = 500
```

**Comment by machakann** [comment]
Ah, excuse me. The timeout feature was broken.

**Comment by machakann** [comment]
Ok now.

**Comment by albertfgu** [comment]
I see, that explains it. I also didn't realize there were 2 other help docs besides `:h sandwich`so I didn't see the external option! Thank you very much, this plugin is fantastic!

**Comment by machakann** [comment]
Sorry, as you pointed out, set `noremap` as `0` is correct. I will correct the above example.
