### ISSUE TITLE
LaTeX "\( ... \)" bun

### ISSUE THREAD

**Issue by albertfgu** [machakann/vim-sandwich#57]
In LaTeX, there is an alternative construct to `$...$` to delimit math mode:
https://tex.stackexchange.com/questions/510/are-and-preferable-to-dollar-signs-for-math-mode

I copied and modified the bun for `\[...\]` and it seems to work for this. Is there a reason it is not a default TeX recipe (perhaps because it is LaTeX-only, and no one really uses it)?

**Comment by machakann** [comment]
Because I'm a beginner of Tex :)

Probably you are right. We should have both.

**Comment by machakann** [comment]
Added in https://github.com/machakann/vim-sandwich/commit/951549e0090d1890cba7640a58fde5dec8bac171
