### ISSUE TITLE
LaTeX environment not detected after nested environment

### ISSUE THREAD

**Issue by albertfgu** [machakann/vim-sandwich#58]
Consider the following LaTeX segment:
```
\begin{itemize}
  \item hello
    \begin{enumerate}
      \item hello
    \end{enumerate}
   *hello
*\end{itemize}
```
The commands `sde` and `sre` don't work when the cursor is on either of the lines marked with `*`, but it works appropriately on all other lines.

I tested this with some other examples, such as further nesting, and other environments such as
```
\begin{equation}
  a
  \begin{bmatrix}
    b
  \end{bmatrix}
 *c
*\end{equation}
```
The behavior is consistent (I also used a minimal vimrc to check): if the cursor is inside an environment but anywhere after an inner nested environment, then the environment is not detected.

**Comment by machakann** [comment]
Thank you for your report! I reproduced this, but it seems very strange because it doesn't happen with other surroundings for example `if` - `end`. I need to look into this more detail. Let me think...

**Comment by machakann** [comment]
Hi, I still don't know why it doesn't work well, but it seems ok if I made a small change to the recipe (though the fix should not change anything in principle). At least, the fix is nothing harmful. So I have already pushed to `master` branch. Please update and try it.

**Comment by albertfgu** [comment]
It seems to work now. I looked at the commit and don't understand; what does the regex `\%(` mean?

**Comment by machakann** [comment]
The pattern `\%(\)` is the grouping almost same as `\(\)` but without capturing. `:help /\%(`

I use `searchpair()`/`searchpairpos()` function of Vim script to search a nested pair, and the document says:

> {start}, {middle} and {end} are patterns, see |pattern|.  They
> must not contain \( \) pairs.  Use of \%( \) is allowed.  When
> {middle} is not empty, it is found when searching from either
> direction, but only when not in a nested start-end pair.  A
> typical use is:
> 	searchpair('\<if\>', '\<else\>', '\<endif\>')
> By leaving {middle} empty the "else" is skipped.

`:help searchpair()`

So probably this was the reason.
