### ISSUE TITLE
Change behaviour of function surround to place the cursor before the first paren

### ISSUE THREAD

**Issue by MageJohn** [machakann/vim-sandwich#61]
I really love the function surround, it fits into my workflow very well. However I think the way it works could be improved. Instead of asking for a function name in the command bar, perhaps the command should insert the parentheses and then put the cursor in front of the opening parenthesis ready for the user to insert a function name. This would result in exactly the same functionality, with the advantage that the user has the full power of whatever completion they have configured. The only difference this makes to the keys pressed is that instead of hitting \<CR\> when the function name has been entered, you hit \<ESC\>.

**Comment by machakann** [comment]
Yes, I love the idea. However, it has a problem with dot-repeating. Probably you can realize the behavior with the following recipe.

```vim
let g:sandwich#recipes = deepcopy(g:sandwich#default_recipes)
let g:sandwich#recipes += [
  \   {
  \     'buns': ['(', ')'],
  \     'cursor': 'head',
  \     'command': ['startinsert'],
  \     'kind': ['add', 'replace'],
  \     'action': ['add'],
  \     'input': ['f']
  \   },
  \ ]
```

After using it, you may find that you cannot repeat by `.` command. This situation is very annoying, but it is quite difficult to hack around insert mode with the current Vim script API.

I really like the `.` command, so the default recipe works like that.

**Comment by MageJohn** [comment]
Oh, I see the issue. Being able to `.` repeat is indeed essential. I might add that recipe under a different letter in order to have both functionalities. I can't test right now, but I will report back later to confirm that you can't `.` repeat it.

**Comment by machakann** [comment]
Sorry, I missed your message. I add a note on the recipe in [wiki](https://github.com/machakann/vim-sandwich/wiki/Magic-characters#function-surroundings), thanks!
