### ISSUE TITLE
Sometimes replacing surroundings do not work as expected 

### ISSUE THREAD

**Issue by KabbAmine** [machakann/vim-sandwich#63]
Having for example the following (where _ is the cursor's position):

```viml
let buffers = filter(range(1, bufnr('$')), 'buflisted(v:val) && getbufvar(v:val, "&filetype") isnot# 'q_f'')
```

Executing `sr'"` will produce:

```viml
let buffers = filter(range(1, bufnr('$')), 'buflisted(v:val) && getbufvar(v:val, "&filetype") isnot# "qf'")
```

But I was expecting:

```viml
let buffers = filter(range(1, bufnr('$')), 'buflisted(v:val) && getbufvar(v:val, "&filetype") isnot# "qf"')
```

-------------------

Same goes for this example, where executing `sr'"` does simply nothing:

```viml
    let buffers = filter(range(1, bufnr('$')), 'buflisted(v:val) && getbufvar(v:val, '&filet_ype'
```

**Comment by machakann** [comment]
Thanks, I reproduced the problem. It seems several problems in quotations searching algorithm are related to the bug. Let me think.

**Comment by machakann** [comment]
Oops, it was rather a simple problem. I tweaked default recipes for quotations. Could you test the latest?

**Comment by KabbAmine** [comment]
Works great for me :+1: 
I'll let you know if there are more cases with single quotes.

Thanks.
