### ISSUE TITLE
Highlighting remains after cancelling with <C-c>

### ISSUE THREAD

**Issue by chaucerbao** [machakann/vim-sandwich#65]
If using \<C-c\> to exit a command that asks for input (ie. `saiwf` or `saiwt`), the visual highlight of the surrounded text remains.

![image](https://user-images.githubusercontent.com/794434/38637557-572e7080-3d80-11e8-8cf9-e5159debe048.png)

Replicate with: `saiwt<C-c>`

**Comment by machakann** [comment]
I make it deleted for sure. However, basically, I cannot guarantee that this plugin works correctly with `<C-c>`. `<C-c>` is not a alternative of `<Esc>`, it quits any running scripts forcibly even halfway. I strongly recommend to use `<Esc>`.
