### ISSUE TITLE
<Plug>(operator-sandwich-add) wrong behavior some multibyte characters

### ISSUE THREAD

**Issue by rapan931** [machakann/vim-sandwich#66]
# Environment

Windows 10

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled May 15 2018 22:14:57)
MS-Windows 64 ビット コンソール 版
適用済パッチ: 1-1848

vim-sandwich hash: 4679a45801837bfb8727c5460cb07d0fe9aa5677

# Reproduce way

_min_vimrc
```vim
let g:sandwich_no_default_key_mappings = 1
let g:operator_sandwich_no_default_key_mappings = 1

packadd vim-sandwich

xmap sa <Plug>(operator-sandwich-add)
```

test.txt
``` txt
a梵aa
```

1. vim -u _min_vimrc -N --noplugin test.txt
2. 0vlsa"

result
`"a梵a"a`

expected
`"a梵"aa`

# other

すみません。日本語で。。
期待通り動作するMultibyte文字もありました。

例:
``` txt
aあaa
```

これは期待通り`"aあ"aa`となりました。

すみませんがご確認よろしくお願いいたします。

**Comment by machakann** [comment]
ありがとうございます。日本語で大丈夫です、タイトルさえ英語なら何となくわかってもらえると思います。

問題も手元で再現しました。まだ原因はわかりませんが、あとで見てみます。

**Comment by machakann** [comment]
思いのほか難しい問題で時間がかかってしまいました。最新版だと正しく動くと思いますので、確認してみてください。

どうやら、 `'encoding'` オプションが cp932 の時に上の問題が起こるようです。 cp932 を使っていると微妙に Vim の動作が怪しいところがあって、ひとまず明らかにおかしい場合だけ迂回するようなコードを入れました。

もし、ほかにもおかしな動作を見つけたらまた issue を建てていただければ嬉しいです。

**Comment by rapan931** [comment]
issue立てた際と同じ環境ではないのですが、以下環境で修正されていることを確認しました。

``` vim
:version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled May  2 2017 12:56:07)
MS-Windows 64 ビット コンソール 版
適用済パッチ: 1-596
Modified by koron.kaoriya@gmail.com
```

また何かありましたら報告させていただきます。
対応ありがとうございました！
