### ISSUE TITLE
In markdown, tag sandwich doesn't insert the angle brackets

### ISSUE THREAD

**Issue by evantravers** [machakann/vim-sandwich#69]
open a markdown file like "foo.md"

Add a random code section like:

```
`this is a code block`
```

put the cursor in there and change the sandwich with `srbtcode<CR>`

I expect: `<code>this is a code block</code>`
I get: `codethis is a code blockcode`

**Comment by machakann** [comment]
You can try `srbTcode<CR>` instead of `srbtcode<CR>`.

Since the input `t` replaces only the name of a tag, instead of entire tag, it inserts only `code`. In case you want to replace a non-tag to a tag, you need to use `T`.

**Comment by evantravers** [comment]
👍
