### ISSUE TITLE
Incorrect behaviour with formatoptions=t

### ISSUE THREAD

**Issue by olmokramer** [machakann/vim-sandwich#70]
The correct text is not sandwiched when any of the edits by vim-sandwich causes a reformatting due to the line being too long.

Reproducer:

1. Open vim without a file: `$ vim`
1. Run `:setl fo+=t tw=10` (formatoptions is now `tcqn1j` for me)
1. Paste this text: `ab cd ef gh ij kl mn op`
1. Position the cursor between the `k` and the `l`
1. Run `saiw(`

The output is now

    ab cd ef)
    gh ij (kl mn op

Note that the closing parenthesis is placed incorrectly.

**Comment by olmokramer** [comment]
Thanks for the quick reply!

> I think it is reasonable to suppress autoformatting in a surrounding operation.

Yeah that's what I thought as well. You should probably also disable `formatoptions=c`. Or were you planning on unsetting `'formatoptions'` altogether?

**Comment by machakann** [comment]
Yes, exactly. I think `formatoptions` would be better to be empty in a operation.

**Comment by machakann** [comment]
I wrote the wrong number in the commit message... But, I think this is fixed by `558b85870657e3a385abd98cea70d6345259d1fc`. Could you update and test it?

**Comment by olmokramer** [comment]
That was fast! Seems to work yes, thanks!
