### ISSUE TITLE
Deleting surroundings does not work when filtering on motionwise

### ISSUE THREAD

**Issue by olmokramer** [machakann/vim-sandwich#72]
I have this recipe in `ftplugin/markdown.vim`

```vim
{ 'buns': ['```', '```'],
\ 'input': ['`'],
\ 'nesting': 0,
\ 'motionwise': ['line'],
\ }
```

So characterwise motions or text objects like `iw` sandwich the text in single `` ` ``s and linewise motions/text objects like `ip` wrap it in `` ``` ``. This is great! But deletion does not work anymore for the single `` ` ``s. If I write this to a markdown file

```md
This is some `code`.
```

And place my cursor in "code", then `` sd` `` does not delete the `` ` ``.

**Comment by machakann** [comment]
Hi, thank you for using vim-sandwich!

This is indeed the difficult (but useful) case. It may be a little lengthy, but could be solved by splitting the recipe into two part; one for addition and the other for deletion.

```vim
let g:sandwich#recipes += [
  \   { 'buns': ['```', '```'],
  \     'input': ['`'],
  \     'nesting': 0,
  \     'motionwise': ['line'],
  \     'action': ['add'],
  \     'kind': ['add', 'replace']},
  \   { 'buns': ['\%(```\|`\)', '\%(```\|`\)'],
  \     'input': ['`'],
  \     'regex': 1,
  \     'nesting': 0,
  \     'action': ['delete'],
  \     'kind': ['delete', `replace`, 'textobj']}
  \ ]
```

**Comment by olmokramer** [comment]
Hi @machakann, thank _you_ for making vim-sandwich!

Thanks for the quick response! Unfortunately that does not work correctly when the cursor is is between a `` ` `` and a `` ``` ``. Take this file for example, where `|` is the cursor position, and the spaces between the `` ` `` are to be ignored

```md
` ` `
This is so|me `code`.
` ` `
```

When I press `` sd` ``, it deletes the `` ``` `` opening the code block, and the `` ` `` before "code". I think a `listexpr` rule is needed here, because the opening bun must be equal to the closing bun. But from the docs it looks like `listexpr` is not supported for deletion?

**Comment by machakann** [comment]
I see. That's a problem. mmm... I think `listexpr` option is also available for a delete action, but I cannot remember why the document doesn't mention it. Let me think.

**Comment by machakann** [comment]
Ah, I remember that we can use the `listexpr` option through the `synchro` option (default true) of textobjects. I found that the documents are not complete. I will update when I have time.

```vim
let g:sandwich#recipes += [
  \   { 'buns': ['```', '```'],
  \     'input': ['`'],
  \     'nesting': 0,
  \     'motionwise': ['line'],
  \     'action': ['add'],
  \     'kind': ['add', 'replace']},
  \   { 'buns': 'Backtick()',
  \     'input': ['`'],
  \     'nesting': 0,
  \     'listexpr': 1,
  \     'linewise': 1,
  \     'action': ['delete'],
  \     'kind': ['delete', 'replace', 'textobj']}
  \ ]

function! Backtick() abort "{{{
  let cursor = [line('.'), col('.')]
  let start = searchpos('\%(^\|[^`]\)`\%([^`]\|$\)', 'bcn', cursor[0])
  let end = searchpos('\%(^\|[^`]\)`\%([^`]\|$\)', 'n', cursor[0])
  if start[0] != 0 && end[0] != 0 && start[1] <= cursor[1] && cursor[1] < end[1]
    return ['`', '`']
  endif

  let start = searchpos('```', 'bcnW')
  let end = searchpos('```', 'nW')
  if start[0] != 0 && end[0] != 0
    return ['```', '```']
  endif

  return ['', '']
endfunction "}}}
```

**Comment by olmokramer** [comment]
Ah, I tried to use a `listexpr` in the recipe, but got an error `Trying to use list as string`, but I had overlooked that when `listexpr` is 1, `buns` should not be a list... And because docs didn't mention the `delete` kind in the `listexpr` section I thought it would be unsupported...

Thanks for the recipe, works like a charm now! Now I want to support variable length sequences of backticks, e.g. ``` `` ` `` ```, which is required to put backticks in the wrapped text. But I'll try that on my own. Thanks for the help!

**Comment by olmokramer** [comment]
Ok I've managed to do that with the function below.

```vim
function! Backtick() abort
	let n = 0

	while 1
		let pat = repeat('`', n + 1)
		let pat_s = '\%(^\|[^`]\)\zs' . pat
		let pat_e = pat . '\ze\_[^`]'

		let [l_s, c_s] = searchpos(pat_s, 'bcnW')
		let [l_e, c_e] = searchpos(pat_e, 'cnW')

		if !l_s || !l_e
			break
		endif

		let past_start = getline(l_s)[c_s + n]
		let before_end = getline(l_e)[c_e - 2]

		if past_start != '`' && before_end != '`'
			let n += 1
			break
		elseif past_start == '`' || before_end == '`'
			let n += 1
		endif
	endwhile

	let bun = repeat('`', n)

	return [bun, bun]
endfunction
```

**Comment by olmokramer** [comment]
Closing this as my specific problem is solved, and I don't think there's a nice way to generalize this. Some people may even expect `` sd` `` to remove the surrounding `` ``` `` instead of the `` ` ``, given the recipe from my first post in this issue. Thanks again for the quick response and the help!

**Comment by olmokramer** [comment]
PS If I set `'action': ['add']` in the recipe, is there any use also setting `'kind': ['add', 'replace']`? Because as far as I understand it, the `'add'` action only applies for the `'add'` and `'replace'` kinds anyway. Or did you add that just as a "safety" measure, in case some other kinds are introduced in the future?

**Comment by machakann** [comment]
Actually, adding `'kind': ['add', 'replace']` is intentional, because `'action': ['add']` doesn't prohibit it to take effect for text-objects. In the first design, `'action'` key doesn't have interaction with text-objects. However, I think this is a design failure. I am going to change this.

I will drop the news here if I make the change.

**Comment by olmokramer** [comment]
Ah I see. Thanks for the explanation. I haven't really used the text-objects feature, so that didn't cross my mind. I'll read up on them and look forward to the new design.

**Comment by machakann** [comment]
OK, you can just use `'action'` filter without `'kind'` filter.

**Comment by olmokramer** [comment]
Ah yes it makes sense to use the same recipes for delete and text objects. Thanks!
