### ISSUE TITLE
Document sandwich#util#addlocal

### ISSUE THREAD

**Issue by olmokramer** [machakann/vim-sandwich#73]
I found the `sandwich#util#addlocal` function when looking at `macros/sandwich/ftplugin/tex.vim`. It looks very useful for filetype plugins, but it is not documented, so I'm unsure if I can safely use it in my config, or that it might change in the future. I had already written a similar function in my config, but it would be nice to use a function that ships with the plugin itself. So my question is if I can consider this function a stable part of the API of sandwich?

**Comment by machakann** [comment]
Thanks. Actually, I've wondered whether it is worth adding or not. OK, you can use safely from now. I added documents and treat it as an official interface.

**Comment by olmokramer** [comment]
Cool, thanks!

**Comment by olmokramer** [comment]
Hmm, the function does not seem to work as expected. I have this in `~/.vim/after/ftplugin/markdown.vim`:

```vim
if !exists('s:sandwich_recipes')
	let s:sandwich_recipes = [{
		\ 'buns': ['```', '```'],
		\ 'input': ['`'],
		\ 'motionwise': ['line'],
		\ 'action': ['add'],
	\ }, {
		\ 'buns': 'sandwich#markdown#backtick()',
		\ 'input': ['`'],
		\ 'listexpr': 1,
		\ 'action': ['delete'],
	\ }]
endif

call sandwich#util#addlocal(s:sandwich_recipes)
```

And this markdown file:

```md
This is a multiline
paragraph.
```

Now when I press  `` saip` `` I get this

```md
`This is a multiline
paragraph.`
```

While I would expect the following output (without the spaces between the backticks)

```md
` ` `
This is a multiline
paragraph.
` ` `
```

So it seems like the default recipes are being prioritized over the local recipes, because `sandwich#util#addlocal` prepends the new recipes to the list instead of appending them. When I append instead with `let b:sandwich_recipes = sandwich#default_recipes + s:sandwich_recipes` then I get the expected behaviour that the local recipe is used.

**Comment by machakann** [comment]
Thank you. I've forgotten that it was the function to add without overriding the user setting, but this is inappropriate now. I have already pushed the fix. Could you update and check again?

**Comment by olmokramer** [comment]
Yes it seems to work now. Thanks again!
