### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by humeniuc** [machakann/vim-sandwich#76]
In the documentation it said that for addition one should use
`sa{motion/textobject}{addition}`.

In the [documentation (L232) ](https://github.com/machakann/vim-sandwich/blob/master/doc/sandwich.txt#L232)
Instead of `` `sa(iw` and `sa)iw` `` shouldn't be `` `saiw(` and `saiw)` ``?
Maybe I am missing something.

**Comment by machakann** [comment]
You are right! Thanks!!
