### ISSUE TITLE
Disable textobj-sandwich?

### ISSUE THREAD

**Issue by for-coursera** [machakann/vim-sandwich#77]
Is it possible not to load the code related to `textobj-sandwich`? I'm using targets.vim, which seem to have some important to me advantages over `textobj-sandwich`, so I don't want them to overlap or to waste resources on startup :)

(But I may also be very wrong and may be it's `textobj-sandwich`, which has something extra over targets.vim?)

Thank you.

**Comment by machakann** [comment]
Don't worry. *Flexibility* is an important goal of this plugin, including the case one wants to disable a part of functions.

It's easy to disable `textobj-sandwich`, just add the line in your vimrc (though large parts of the source codes are loaded on the first use of `textobj-sandwich` thus it may not reduce startup time so much).

```vim
let g:textobj_sandwich_no_default_key_mappings = 1
```

Thank you for using!
