### ISSUE TITLE
Custom Magic characters?

### ISSUE THREAD

**Issue by antaed** [machakann/vim-sandwich#78]
Is there any way to create custom Magic characters? For example, I added the entry below to **g:sandwich#recipes** but if possible, I would like to use **ciP** instead of **cisP**:
`{'buns': ['<?php\s*', '\s*?>'], 'regex': 1, 'filetype': ['php'], 'input': ['P']}`

P.S. Amazing work mate, I was pretty happy with my config for quite some time but your plugin is too good not to have it installed

**Comment by machakann** [comment]
Thank you! The easiest way is maybe this:

```vim
omap iP isP
xmap iP isP
omap aP asP
xmap aP asP
```

Or you can make new key-mappings that don't depend on **g:sandwich#recipes**.

```vim
omap <expr><silent> iP textobj#sandwich#auto('o', 'i', {}, [{'buns': ['<?php\s*', '\s*?>'], 'regex': 1, 'filetype': ['php']}])
xmap <expr><silent> iP textobj#sandwich#auto('x', 'i', {}, [{'buns': ['<?php\s*', '\s*?>'], 'regex': 1, 'filetype': ['php']}])
omap <expr><silent> aP textobj#sandwich#auto('o', 'a', {}, [{'buns': ['<?php\s*', '\s*?>'], 'regex': 1, 'filetype': ['php']}])
xmap <expr><silent> aP textobj#sandwich#auto('x', 'a', {}, [{'buns': ['<?php\s*', '\s*?>'], 'regex': 1, 'filetype': ['php']}])
```

**Comment by antaed** [comment]
that'll do, thanks!
