### ISSUE TITLE
Problem with dein

### ISSUE THREAD

**Issue by taigacute** [machakann/vim-sandwich#79]
I use dein to lazyload plugins.  the lazyload feature of dein dosent load the default config of plugins.  i saw the keymap of `vim-sandwich` is too much .has `operator` `textobj` `sandwich`,  i can create a keymap for `vim-sandwich`,but i am new for this plugins. i am afraid of miss some keymap . so  can you give the complete defult keymap  list?

**Comment by machakann** [comment]
* add
  - <kbd>sa</kbd> (normal, visual)
* delete
  - <kbd>sd</kbd> (normal, visual)
  - <kbd>sdb</kbd> (normal)
* replace
  - <kbd>sr</kbd> (normal, visual)
  - <kbd>sdb</kbd> (normal)
* text-object
  - <kbd>ib</kbd> (operator-pending, visual)
  - <kbd>ab</kbd> (operator-pending, visual)
  - <kbd>is</kbd> (operator-pending, visual)
  - <kbd>as</kbd> (operator-pending, visual)

Key-mapped modes are shown inside parenthesis. I am not very sure, is it what you need?

**Comment by taigacute** [comment]
no,  i set this .but didnt work
```
 nnoremap <silent> sa :<C-u>call operator#sandwich#keymap('add', 'n')<CR>
 xnoremap <silent> sa <Esc>:call operator#sandwich#keymap('add', 'x')<CR>
nmap <silent> sd <Plug>(operator-sandwich-delete)<Plug>(operator-sandwich-release-count)<Plug>(textobj-sandwich-query-a)
nmap <silent> sdb <Plug>(operator-sandwich-delete)<Plug>(operator-sandwich-release-count)<Plug>(textobj-sandwich-auto-a)
 nmap <silent> sr <Plug>(operator-sandwich-replace)<Plug>(operator-sandwich-release-count)<Plug>(textobj-sandwich-query-a)
    nmap <silent> srb <Plug>(operator-sandwich-replace)<Plug>(operator-sandwich-release-count)<Plug>(textobj-sandwich-auto-a)
    omap ia <Plug>(textobj-sandwich-auto-i)
	xmap ia <Plug>(textobj-sandwich-auto-i)
	omap aa <Plug>(textobj-sandwich-auto-a)
	xmap aa <Plug>(textobj-sandwich-auto-a)
    onoremap <silent><expr> ib textobj#sandwich#auto('o', 'i')
	xnoremap <silent><expr> ib textobj#sandwich#auto('x', 'i')
	onoremap <silent><expr> ab textobj#sandwich#auto('o', 'a')
	xnoremap <silent><expr> ab textobj#sandwich#auto('x', 'a')

```

**Comment by taigacute** [comment]
hmm `vim-sandwich` seems like difficult to lazyload with dein....

**Comment by machakann** [comment]
The above setting looks ok. Maybe it would be better to check two things:

1. vim-sandwich plugin directory is in `&runtimepath`; you can check by `:echom &rtp`
1. three plugin files are listed in the output of `:filter/sandwich.vim/scriptnames` or not
  - plugin/operator/sandwich.vim
  - plugin/sandwich.vim
  - plugin/textobj/sandwich.vim

I still didn't understand the problem, probably the plugin does not properly loaded in some reason? If you can provide the *minimal* vimrc to reproduce the problem, it would be easier to help.

**Comment by taigacute** [comment]
@machakann  dein doesnt load the default config of plugin. so it dosent add plugins/xx file.

**Comment by taigacute** [comment]
minal vimrc
```VIML
if &compatible
  set nocompatible
endif
" Add the dein installation directory into runtimepath
set runtimepath+=~/.config/nvim/repos/github.com/Shougo/dein.vim

if dein#load_state('~/.cache/dein')
  call dein#begin('~/.cache/dein')

  call dein#add('machakann/vim-sandwich', {'on_map': { 'vnox': '<Plug>'}})

  call dein#end()
  call dein#save_state()
  if dein#check_install()
     call dein#install()
  endif
endif

filetype plugin indent on
syntax enable
if dein#tap('vim-sandwich')
     nmap <silent> sa <Plug>(operator-sandwich-add)
     xmap <silent> sa <Plug>(operator-sandwich-add)
     omap <silent> sa <Plug>(operator-sandwich-g@)
     nmap <silent> sd <Plug>(operator-sandwich-delete)<Plug>(operator-sandwich-release-count)<Plug>(textobj-sandwich-query-a)
     xmap <silent> sd <Plug>(operator-sandwich-delete)
     nmap <silent> sr <Plug>(operator-sandwich-replace)<Plug>(operator-sandwich-release-count)<Plug>(textobj-sandwich-query-a)
     xmap <silent> sr <Plug>(operator-sandwich-replace)
     nmap <silent> sdb <Plug>(operator-sandwich-delete)<Plug>(operator-sandwich-release-count)<Plug>(textobj-sandwich-auto-a)
     nmap <silent> srb <Plug>(operator-sandwich-replace)<Plug>(operator-sandwich-release-count)<Plug>(textobj-sandwich-auto-a)
endif
```

**Comment by machakann** [comment]
`plugin/**/*.vim` are the files to define essential interfaces. Generally, there is no guarantee that a plugin works properly without load those files, though some plugins may work if you copy some key-mappings into vimrc. If those files were not loaded, there is definitely something wrong (maybe) with settings.

Probably, you can find a way to load those files when you need. I'm not familiar with dein but it seems automatic lazy-loading keymapping generation of `'on_map'` is not always perfect. Isn't it like this?

```vim
  call dein#add('machakann/vim-sandwich', {'on_map': { 'nox': ['<Plug>(operator-sandwich-', '<Plug>(textobj-sandwich-']}})
```

**Comment by taigacute** [comment]
yes 。 so  i lazyload by `on_ft:[python,go.javascript]` .it can work.

**Comment by taigacute** [comment]
@machakann   by the way ，Is this key mapp complete? did i missed some feature keymap ?
```VIML
if dein#tap('vim-sandwich')
     nmap <silent> sa <Plug>(operator-sandwich-add)
     xmap <silent> sa <Plug>(operator-sandwich-add)
     omap <silent> sa <Plug>(operator-sandwich-g@)
     nmap <silent> sd <Plug>(operator-sandwich-delete)<Plug>(operator-sandwich-release-count)<Plug>(textobj-sandwich-query-a)
     xmap <silent> sd <Plug>(operator-sandwich-delete)
     nmap <silent> sr <Plug>(operator-sandwich-replace)<Plug>(operator-sandwich-release-count)<Plug>(textobj-sandwich-query-a)
     xmap <silent> sr <Plug>(operator-sandwich-replace)
     nmap <silent> sdb <Plug>(operator-sandwich-delete)<Plug>(operator-sandwich-release-count)<Plug>(textobj-sandwich-auto-a)
     nmap <silent> srb <Plug>(operator-sandwich-replace)<Plug>(operator-sandwich-release-count)<Plug>(textobj-sandwich-auto-a)
endif
```

**Comment by machakann** [comment]
It depends on you. The above settings completes the operator side. If you also need text-objects, add the following lines. If not, then ok.

```vim
omap ib <Plug>(textobj-sandwich-auto-i)
xmap ib <Plug>(textobj-sandwich-auto-i)
omap ab <Plug>(textobj-sandwich-auto-a)
xmap ab <Plug>(textobj-sandwich-auto-a)

omap is <Plug>(textobj-sandwich-query-i)
xmap is <Plug>(textobj-sandwich-query-i)
omap as <Plug>(textobj-sandwich-query-a)
xmap as <Plug>(textobj-sandwich-query-a)
```

**Comment by taigacute** [comment]
ok  i got it.
