### ISSUE TITLE
Operator `sd'` `sd"` don't work at some filetypes

### ISSUE THREAD

**Issue by ichizok** [machakann/vim-sandwich#8]
Vim 7.4.811

vimrc:

```vim
set rtp+=/path/to/vim-sandwich
syntax on
```

```
vim -u vimrc -N
:set ft=sh
i"foo"<Esc>h
sd"
```

* or `ft=ruby`
* cursor is on `"fo[o]"`

Expected:

```
foo
```

Actual:

```
"foo"
```

* cursor moved to `"f[o]o"`

**Comment by ichizok** [comment]
I think this is due to the difference of syntax group ID.

At `ft=sh`, 

`["]foo"` (double-quote, `shQuote`) syntax group ID is `Statement`.
`"[f]oo"` (inner string, `shDoubleQuote`) syntax group ID is `Constant`.

(result of `synIDattr(synIDtrans(synID(*, *, 1)), "name")`)

https://github.com/machakann/vim-sandwich/blob/ca96b9f6f68fc0521c5a1539d54fb0b8813cdd9c/autoload/textobj/sandwich.vim#L640

```
synstack_inner_head : ['Constant']
synstack_inner_tail : ['Constant']
self.syntax : ['Statement']
```

so `opt_match_syntax_affair` is false, then `self.is_valid_candidate()` becomes false.

https://github.com/machakann/vim-sandwich/blob/ca96b9f6f68fc0521c5a1539d54fb0b8813cdd9c/autoload/textobj/sandwich.vim#L444

**Comment by machakann** [comment]
Thank you for your detailed report. You are totally right and it looks problemsome.

The underlying problem was in the default recipes. Since I set `match_syntax` option as 2 for `''` and `""`, operaors check characters inside also.
```vim
" default settings for quotes
        [
      \   {'buns': ['"', '"'], 'quoteescape': 1, 'expand_range': 0, 'nesting': 0, 'match_syntax': 2},
      \   {'buns': ["'", "'"], 'quoteescape': 1, 'expand_range': 0, 'nesting': 0, 'match_syntax': 2},
      \ ]
```

I will change them as 1 to check only the both edge quotes.

**Comment by machakann** [comment]
As for the problem on the cursor position, it looks related to a recent commit (b72ada888cf19dc39f80b33b3de142b73c9dd09f). I guess it is fixed now.

**Comment by machakann** [comment]
Ah... Sorry, I might change the way to solve. Because it might be unuseful for the list expression.
```ruby
list = ['foo', 'bar']
```
If the cursor is in between the list items, `['foobar']` would be shown by a key sequence `sd'` unexpectedly, while `'foo', 'bar'` is expected.

Let me think for better ways.

**Comment by machakann** [comment]
I made mistake, so I correct the last comment.

**Comment by machakann** [comment]
Hi, I finally add a new local option `'inner_syntax'`, similar as `'syntax'` option, and use it instead of the previous 'matched_syntax' option for the default recipes. I think it can go well with ruby and shell script now.

**Comment by ichizok** [comment]
Thank you for your support, but I think it should be not `'String'` but `'Constant'`.
https://github.com/machakann/vim-sandwich/blob/91319711cf8e5158e5c2e350f30ee4dc8e09141b/autoload/sandwich.vim#L13-L14

The result of `synIDtrans(<synID of 'String'>)` is `Constant`.

Additionally, now they (`sd", sd'`) don't work within comment.
It resolves by appending `'Comment'` to `inner_syntax`, but it causes https://github.com/machakann/vim-sandwich/issues/8#issuecomment-129012679 problem again.

**Comment by machakann** [comment]
I didn't realize that because of my colorscheme but, yes, it should be `'Constant'`. I hasten to update for the problem (6d873247e5a60c5077084cf13a382bff2ee5c72f).

As for the problem in `'Comment'`, it looks not easy to solve. Therefore I just add `'Comment'` for now, and I stack it as future work.

**Comment by machakann** [comment]
I found the syntax option makes problems with other filetypes, like markdown. Thus I have finally given up to use syntax options for default recipes. I will keep only writing notes in documents.

Excuse me for changing of my mind.

**Comment by machakann** [comment]
The unintended cursor movement when an action fails had not been fixed. Now it is OK.
Probably all the problem has been fixed up now. I will close this issue.
