### ISSUE TITLE
TeX marks \bigl* ... \bigr* in place of \big*

### ISSUE THREAD

**Issue by BertrandSim** [machakann/vim-sandwich#82]
In the TeX recipes, I believe that `\big( ... \big)`, `\big[ ... \big]` etc., should be replaced with `\bigl( ... \bigr)` , `\bigl[ ... \bigr]` etc. Refer to [this post](https://tex.stackexchange.com/questions/19480/why-use-the-control-sequences-bigl-biggl-bigr-or-biggr-as-i-can-always-us/144439) for details. To summarize, "`\bigl` informs TeX that the subsequent "fence symbol" -- `(`, `[`, `\{`, etc -- is to be given math-class "Math Open" rather than "Math Ordinary"." A similar thing can be said for `bigr`, which declares the next symbol as a closing delimiter instead of an ordinary delimiter.

**Comment by machakann** [comment]
Thank you, really good catch. I didn't know this. (I wonder is there any case `\big*` is prior to `\bigl*`?) Probably, you are right. I will merge the fix this weekend if there is no objection.

**Comment by lervag** [comment]
In vimtex, I've decided to not support the `\big` variants for the same reason. I think this is a sensible request. If you stop supporting the `\big(...\big)` in favor for `\bigl(...\bigr)` family of modifiers will help make people learn to write proper LaTeX. :)

**Comment by BertrandSim** [comment]
@machakann Most welcome. tbh, I raised this issue after reading a similar past issue in vimtex. BTW, thank you for this wonderful plugin :)

**Comment by machakann** [comment]
Merged. Thank you!
