### ISSUE TITLE
Normal mode commands beep

### ISSUE THREAD

**Issue by dolio** [machakann/vim-sandwich#9]
I noticed that several of the normal mode commands beep when you use them. This is because they are using `<Esc>`, and if there is no count, there is nothing to cancel.

I think this is easy to fix, but it takes changes in a couple places. First, instead of mappings like:

    nnoremap <Plug>(...) <Esc>:call ...

use:

    nnoremap <Plug>(...) :<C-U>call ...

The `<C-U>` will kill the range arguments that get inserted due to any counts. However, `operator#sandwich#prerequisite` expects the `<Esc>` behavior, by looking at `v:prevcount`, so with the `<C-U>` option, I think you should instead look at `v:count1` (or `v:count`, but you're emulating the behavior of `v:count1` anyway). I suspect the `xmap` bindings would have to use `<C-U>` in this case as well, which should be fine.

This works for the use cases I've tested (the ones I have). Hopefully it's good enough in general.

**Comment by machakann** [comment]
Thanks!

This `<Esc>` is mainly for storing the correct cursor position in visual mode (there is an option to save and restore the cursor position after an operation. See issue #3 ). However, indeed, it is not reasonable for normal mode.  I modified the mappings as you told only in normal mode and optimize `operator#sandwich#prerequisite()` a bit. I guess they works fine now, please try.

**Comment by dolio** [comment]
Looks good. Thanks.

**Comment by dolio** [comment]
Oops, I found one more case that beeps. In `operator#sandwich#prerequisite`, the branch for block visual mode has a line (169):

    execute "normal! \<Esc>"

Thing seem to work correctly if I comment out this line, but I'm unsure how it affects issue #3.

**Comment by machakann** [comment]
You are right! And I found that the line is not required anymore. I just remove it.

**Comment by dolio** [comment]
Okay, looks good. I haven't found any other bells.
