### ISSUE TITLE
surround + arrowkey by accident

### ISSUE THREAD

**Issue by cridemichel** [machakann/vim-sandwich#90]
if I want to surround a word like 

```text
  X
pippo
```
(where X is the cursor position) by using "saaw" and I accidentally press an arrow key
I get the following mess:

```text
 <t_><t_>pippo
```
is there any problem with my vim configuration or is it a vim-sanwhich issue?

thank you
Cristiano

**Comment by machakann** [comment]
Thank you. I reproduced the problem, this is interesting.

**Comment by machakann** [comment]
It should be fixed by  02e3b6d. Please tell me if not. Thank you for your report!

**Comment by cridemichel** [comment]
yes it is thank you for the prompt fix and the vey nice plugin!

Cristiano De Michele
cristiano.demichele@gmail.com
