### ISSUE TITLE
Is it time to tag/release 1.0?

### ISSUE THREAD

**Issue by 1ace** [machakann/vim-sandwich#91]
There hasn't been much activity for the last year; looks like the project is ready for a `1.0` release :tada:

**Comment by machakann** [comment]
Thanks for your kind suggestion. It would be ok for me, but I would like to clear a few issues before it if possible. Right now, I'm a little busy with my personal business. So, I would release v1.0, probably, May or July this year.

**Comment by machakann** [comment]
Tagged.
