### ISSUE TITLE
Unable to delete/replace double curly brackets in Typescript React props

### ISSUE THREAD

**Issue by MKennelly** [machakann/vim-sandwich#93]
I recently switched from vim-surround to give this a try. Generally like it and would like to stick with it, but I have run into one problem that I haven't seen documented in any other issues.

vim-sandwich version: commit 02e3b6d1ff9ce346c115166855137b318b63c536
neovim v0.4.3

When I have double curly brackets for a prop inside of tag element (html or React component), I am unable to operate on the curly brackets at all. Single curly brackets are fine, and this exact same format inside of a `.js` or `.jsx` file seem to work fine so I think it may be specific to typescript files/syntax.

Simplest example (`Component.tsx`):
```tsx
const Component: React.FC = () => {
  return <div style={{ margin: 0 }} />;
};
```
If I have my cursor anywhere inside of the double curly brackets, `sdb` deletes the `< ` and `>` at the start and end of the tag. `sd{` and `sd}` don't do anything, and `sr{*` and `sr}*` also do nothing.

Likely the same issue, but just for extra info it is the same issue if the prop is on its own line:
```tsx
const Component: React.FC = () => {
  return (
    <div
      style={{ margin: 0 }}
    />
  );
};
```
In this case `sdb` deletes the surrounding `(`,`)` instead of the tag open and close `<`,`>`, `sd{` and `sd}` do nothing, and the replace command still does nothing.

**Comment by machakann** [comment]
Probably, that's because of the unbalanced syntax coloring. I have relaxed the condition, please try the latest commit (bb5a3270ed010e0fe3343945c8d1f6c814341d72).

**Comment by MKennelly** [comment]
Worked like a charm, thanks so much!
