### ISSUE TITLE
How to change HTML tag?

### ISSUE THREAD

**Issue by yyq123** [machakann/vim-sandwich#96]
Hi @machakann

I want to change the `<p>` tag to `<div>`

After issue the `srt` command, I can input ONLY ONE letter "D". 

![plugin_sandwich_srt](https://user-images.githubusercontent.com/312427/87437452-eca96900-c620-11ea-9d80-fb9f7f9a20d7.gif)

How to input multiple letters for the new tag?

Please help. Thanks.

**Comment by machakann** [comment]
Hi, @yyq123 . Thank you for using!

The `sr` command in principle takes two additional inputs `sr{replaced}{replacement}`, like `sr[(`. It represents "replace [] to ()". So please try `srtt`, double `t`, it will replace a HTML like tag to another tag. If you feel it lengthy you can make a short hand.

```
nmap srt <Plug>(operator-sandwich-replace)<Plug>(textobj-sandwich-query-a)tt
```

The command allows you to do the same thing with `srt`.

**Comment by yyq123** [comment]
It's very logical.

Thank you for your clarification.
