### ISSUE TITLE
Cannot delete HTML tag

### ISSUE THREAD

**Issue by yyq123** [machakann/vim-sandwich#98]
Hi @machakann

As the below screenshot shows, cannot delete a HTML tag using `sdt` and `sdT` command.

![plugin_sandwich_sdt](https://user-images.githubusercontent.com/312427/87896278-52ab4b80-ca7a-11ea-9dcc-5ffd0cf9f45b.gif)

Please help. Thanks.

**Comment by machakann** [comment]
This seems a bug. What is the output of `set selection?` ?

**Comment by yyq123** [comment]
selection=exclusive

**Comment by yyq123** [comment]
set selection=inclusive, and try again, it seems work
![plugin_sandwich_sdt_new](https://user-images.githubusercontent.com/312427/88362614-b8b40d80-cdaf-11ea-8521-1e11de57c1a6.gif)

but it does not work in nested tags
![plugin_sandwich_sdt_new_nested](https://user-images.githubusercontent.com/312427/88363147-93c09a00-cdb1-11ea-9116-48a72b1004e8.gif)

**Comment by machakann** [comment]
Thanks, I pushed a fix for this problem. Could you please test the latest one (ce24d28819d5d0e47f3072a687117fe31ce893a5)?

**Comment by yyq123** [comment]
@machakann Everything is OK now. Thank you for your help!

**Comment by yyq123** [comment]
Problem solved!
